package storage

import (
	"context"
	"fmt"
	"time"

	"github.com/pgvector/pgvector-go"
)

// The feedback event log (#251, docs/feedback-events.md). Hand-written on the
// pgx pool rather than generated by sqlc for the same reason vector.go is: the
// event snapshots a copy of the article's embedding, and sqlc does not model
// pgvector's vector type. The vector type is registered per pooled connection
// in pool.go, so it binds and scans natively here.
//
// Every write is a single INSERT ... SELECT that gathers the prediction
// provenance in the same statement. That is deliberate: a read-modify-write
// would race the AI pipeline rewriting interest_score, and a later join would
// reconstruct today's prediction instead of the one the reader reacted to.

// FeedbackKind identifies the code path that produced a feedback event. The
// distinction is the point of the table -- several paths all set
// read_state.read = TRUE and they mean opposite things. Never collapse these.
type FeedbackKind string

const (
	// FeedbackArticleOpened is the reader opening an article from a list. They
	// chose this one out of everything on offer: genuine engagement.
	FeedbackArticleOpened FeedbackKind = "article_opened"
	// FeedbackReadToggledOn is an explicit "mark read" without opening --
	// deliberate dismissal, a weak negative.
	FeedbackReadToggledOn FeedbackKind = "read_toggled_on"
	// FeedbackReadToggledOff is marking an article unread again: the reader
	// wants it back, a weak positive.
	FeedbackReadToggledOff FeedbackKind = "read_toggled_off"
	// FeedbackBulkDismissed is queue bankruptcy -- mark-all-read, group
	// mark-read, summary mark-read. It carries NO interest signal. It is
	// recorded only so the other kinds are not contaminated by it, and any
	// consumer must weight it zero.
	FeedbackBulkDismissed FeedbackKind = "bulk_dismissed"
	// FeedbackExternalRead is a Fever API item mark. Third-party clients
	// auto-mark on scroll with behavior Herald does not control and cannot
	// introspect, so this cannot be trusted as engagement the way
	// FeedbackArticleOpened can.
	FeedbackExternalRead FeedbackKind = "external_read"
	// FeedbackExternalBulkRead is a Fever feed/group/all mark: bulk dismissal
	// through the API.
	FeedbackExternalBulkRead FeedbackKind = "external_bulk_read"
	// FeedbackStar and FeedbackUnstar are a strong positive and its retraction
	// (an unstar is not a negative).
	FeedbackStar   FeedbackKind = "star"
	FeedbackUnstar FeedbackKind = "unstar"
	// FeedbackGroupMute is "enough of THIS STORY", not a standing topic ban --
	// a negative on the cluster that should decay quickly.
	FeedbackGroupMute FeedbackKind = "group_mute"
	// FeedbackGroupDisband says the grouping was wrong: a label on similarity,
	// not on interest.
	FeedbackGroupDisband FeedbackKind = "group_disband"
	// FeedbackFeedUnsubscribe is feed-level, and is NOT necessarily a content
	// judgment -- dead feeds, format changes, and volume cuts all land here.
	// Consumers must check FeedStatus/FeedErrors before mining it as a
	// negative.
	FeedbackFeedUnsubscribe FeedbackKind = "feed_unsubscribe"
	// FeedbackSearchResultClick pairs a query with a chosen result.
	FeedbackSearchResultClick FeedbackKind = "search_result_click"
	// FeedbackVoteUp and FeedbackVoteDown are the explicit controls (#252):
	// the reader stating an opinion rather than Herald inferring one. These are
	// the anchor the implicit signals calibrate against, and they are the only
	// kinds that can carry a reason.
	FeedbackVoteUp   FeedbackKind = "vote_up"
	FeedbackVoteDown FeedbackKind = "vote_down"
	// FeedbackVoteCleared is a retracted vote. Like FeedbackUnstar it is a
	// withdrawal, not an opposite: clearing a downvote does not mean the reader
	// liked the article.
	FeedbackVoteCleared FeedbackKind = "vote_cleared"
	// FeedbackClickthrough is the reader leaving for the original site. A
	// positive, but one that must be read against ContentLength: on a truncated
	// stub, clicking out is the only way to read the article at all, so it
	// barely outranks a passive read. On a full-text article it means the
	// reader wanted the source, which is a much stronger statement.
	FeedbackClickthrough FeedbackKind = "clickthrough"
)

// Reason axes for an explicit vote (#252). Optional: a bare vote is a valid
// label, and forcing a reason gets a random one.
//
// These deliberately do NOT reuse filter_rules.axis, which is constrained to
// author/category/tag and cannot express three of the five reasons a reader
// actually gives. Mining these into rules (#254) is therefore a translation
// step, not a direct copy.
type FeedbackAxis string

const (
	// AxisTopic is "not this subject". The strongest content signal here.
	AxisTopic FeedbackAxis = "topic"
	// AxisFeed is "not from this feed" -- about the publisher, not the subject.
	AxisFeed FeedbackAxis = "feed"
	// AxisSource is "not this linked-to domain", the site an aggregator points
	// at rather than the aggregator itself.
	AxisSource FeedbackAxis = "source"
	// AxisDuplicate is "already saw this". Not a judgment on the content at
	// all: the reader wanted it once. Consumers must not mine it as a topic
	// negative.
	AxisDuplicate FeedbackAxis = "duplicate"
	// AxisTiming is "wrong for me right now" -- interest without appetite. It
	// should decay fast and must never harden into a standing rule.
	AxisTiming FeedbackAxis = "timing"
)

// Reason axes for an unsubscribe (#252). Most unsubscribes are not content
// judgments, and treating them as one teaches the model to avoid topics
// because a server went away.
const (
	// AxisFeedBroken is a dead or malformed feed. Never a content negative.
	AxisFeedBroken FeedbackAxis = "broken"
	// AxisFeedVolume is "too much of it", not "wrong subject". At most a
	// frequency signal.
	AxisFeedVolume FeedbackAxis = "volume"
	// AxisFeedNotInterested is the only unsubscribe reason that may propagate
	// as a content negative -- and even then, only when the feed was healthy.
	AxisFeedNotInterested FeedbackAxis = "not_interested"
)

// validVoteAxes and validUnsubscribeAxes are closed sets. The axis arrives from
// a form field, so it is validated rather than trusted: an unchecked value
// would let a caller write arbitrary strings into the training corpus, and a
// consumer grouping by axis would silently split on typos.
var validVoteAxes = map[FeedbackAxis]bool{
	AxisTopic: true, AxisFeed: true, AxisSource: true,
	AxisDuplicate: true, AxisTiming: true,
}

var validUnsubscribeAxes = map[FeedbackAxis]bool{
	AxisFeedBroken: true, AxisFeedVolume: true, AxisFeedNotInterested: true,
}

// ValidVoteAxis reports whether a is a recognized vote reason. An empty axis is
// valid: it means the reader voted without giving a reason.
func ValidVoteAxis(a string) bool {
	return a == "" || validVoteAxes[FeedbackAxis(a)]
}

// ValidUnsubscribeAxis reports whether a is a recognized unsubscribe reason.
// Empty is valid and is the default -- an unlabeled unsubscribe is honest,
// a guessed one is not.
func ValidUnsubscribeAxis(a string) bool {
	return a == "" || validUnsubscribeAxes[FeedbackAxis(a)]
}

// FeedbackSurface is where the interaction happened. Fever traffic in
// particular has to stay separable: its read marks come from clients whose
// auto-mark behavior Herald neither controls nor observes.
type FeedbackSurface string

const (
	SurfaceWebList    FeedbackSurface = "web-list"
	SurfaceWebArticle FeedbackSurface = "web-article"
	SurfaceWebSearch  FeedbackSurface = "web-search"
	SurfaceWebGroup   FeedbackSurface = "web-group"
	SurfaceWebSummary FeedbackSurface = "web-summary"
	SurfaceWebFeeds   FeedbackSurface = "web-feeds"
	SurfaceFever      FeedbackSurface = "fever"
)

// FeedbackEvent is one recorded interaction. The caller supplies what only it
// knows -- which code path fired, which surface, where in the list the article
// sat -- and the storage layer snapshots the prediction provenance.
type FeedbackEvent struct {
	UserID    int64
	ArticleID int64 // 0 for feed-scoped events
	FeedID    int64 // used by feed-scoped events; article events derive it
	Kind      FeedbackKind
	Surface   FeedbackSurface

	// Axis and AxisValue mirror filter_rules, populated when the reader gave a
	// reason. Passive collection leaves them empty.
	Axis      string
	AxisValue string

	// ListPosition is 1-based rank in the rendered list, nil when there was no
	// list. Items near the top are opened more regardless of quality; without
	// this a model learns "be at the top" and nothing else.
	ListPosition *int

	// Exploration marks an article that was deliberately surfaced despite a low
	// score. Upvotes on these are the only observable evidence of false
	// negatives.
	Exploration bool
}

// FeedbackEventRow is a stored event read back, including the snapshotted
// provenance.
type FeedbackEventRow struct {
	ID            int64
	UserID        int64
	ArticleID     *int64
	FeedID        *int64
	ArticleTitle  *string
	ArticleURL    *string
	Kind          string
	Axis          *string
	AxisValue     *string
	InterestScore *float64
	ScoreModel    *string
	PromptHash    *string
	// RulesFired is raw JSONB: the filter rules that adjusted this article's
	// score (#259), or nil when none matched. Left unparsed deliberately --
	// the Go-side shape is a consumer concern and there is no consumer yet.
	RulesFired   []byte
	ListPosition *int
	Surface      string
	Exploration  bool
	FeedStatus   *string
	FeedErrors   *int
	// ContentLength is how much body text the reader had in Herald, and
	// HasFullText whether the linked article had been fetched. Together they
	// gate how much a clickthrough is worth and make dwell interpretable.
	ContentLength *int
	HasFullText   *bool
	CreatedAt     time.Time
	HasEmbedding  bool
}

// insertArticleFeedback snapshots provenance for article-scoped events.
//
// score_model and prompt_hash are copied forward from read_state, where the
// curation stage wrote them at scoring time (#258). They are deliberately NOT
// re-derived from user_prompts here: that would resolve the prompt in force
// when the READER acted, which is a different prompt whenever one was edited
// between scoring and reading -- precisely when the labels matter most. NULL
// means the score predates provenance recording and its origin is unknown; it
// does not mean "the current prompt".
//
// content_length counts the body the reader could actually see in Herald: the
// feed's content (falling back to the summary when the feed sends none) plus
// any fetched full text. has_full_text says whether the linked article had been
// fetched at all. A stub post is a short content_length with no full text, and
// on one of those a clickthrough is close to mandatory rather than a choice.
//
// rules_fired records the filter rules that moved this article's score (#259).
// It snapshots at INTERACTION time rather than scoring time, which is correct
// under the query-time design: the rules were part of the score the reader was
// actually shown. jsonb_agg over no rows yields SQL NULL, which is the wanted
// encoding for "no rules fired" -- better than writing an empty array on every
// event for every user who has no rules.
//
// The join to user_feeds is the subscription guard: an event may only be
// recorded for an article in a feed the user subscribes to, matching the
// article-access gate in plan 003. An unsubscribed article inserts nothing.
var insertArticleFeedback = `
INSERT INTO feedback_events (
    user_id, article_id, feed_id, article_title, article_url, embedding,
    kind, axis, axis_value,
    interest_score, score_model, prompt_hash, rules_fired,
    list_position, surface, exploration, feed_status, feed_errors,
    content_length, has_full_text)
SELECT
    $1, a.id, a.feed_id, a.title, a.url, ae.embedding,
    $3, NULLIF($4, ''), NULLIF($5, ''),
    rs.interest_score, rs.score_model, rs.prompt_hash, frs.rules,
    $6, $7, $8, f.status, f.consecutive_errors,
    length(COALESCE(NULLIF(a.content, ''), a.summary, '')) + length(COALESCE(a.linked_content, '')),
    COALESCE(a.linked_content, '') <> ''
FROM articles a
JOIN user_feeds uf ON uf.feed_id = a.feed_id AND uf.user_id = $1
LEFT JOIN article_embeddings ae ON ae.article_id = a.id
LEFT JOIN read_state rs ON rs.article_id = a.id AND rs.user_id = $1
LEFT JOIN feeds f ON f.id = a.feed_id
LEFT JOIN LATERAL (
    SELECT jsonb_agg(jsonb_build_object(
               'rule_id', fr.id,
               'axis',    fr.axis,
               'value',   fr.value::text,
               'score',   fr.score,
               'feed_id', fr.feed_id
           ) ORDER BY fr.id) AS rules
    FROM filter_rules fr
    WHERE ` + filterRuleMatch("$1") + `
) frs ON TRUE
WHERE a.id = ANY($2::bigint[])`

// RecordFeedbackEvent appends one article-scoped event. An event for an article
// that no longer exists inserts nothing rather than erroring: feedback is
// best-effort and must never fail the interaction that produced it.
func (s *PostgresStore) RecordFeedbackEvent(ev FeedbackEvent) error {
	if ev.ArticleID == 0 {
		return fmt.Errorf("record feedback %q: no article id", ev.Kind)
	}
	return s.recordArticleFeedback(ev, []int64{ev.ArticleID})
}

// RecordFeedbackEventsBatch appends one event per article in a single
// statement. Bulk dismissal is recorded per-article, not as one row with a
// count: which articles the reader declined to open before clearing the queue
// is itself the informative part.
func (s *PostgresStore) RecordFeedbackEventsBatch(ev FeedbackEvent, articleIDs []int64) error {
	if len(articleIDs) == 0 {
		return nil
	}
	return s.recordArticleFeedback(ev, articleIDs)
}

func (s *PostgresStore) recordArticleFeedback(ev FeedbackEvent, articleIDs []int64) error {
	_, err := s.pool.Exec(context.Background(), insertArticleFeedback,
		ev.UserID, articleIDs, string(ev.Kind), ev.Axis, ev.AxisValue,
		ev.ListPosition, string(ev.Surface), ev.Exploration)
	if err != nil {
		return fmt.Errorf("record feedback %q for user %d: %w", ev.Kind, ev.UserID, err)
	}
	return nil
}

// RecordFeedFeedbackEvent appends a feed-scoped event (unsubscribe), snapshotting
// the feed's health so a consumer can tell a dead-feed cleanup from a content
// judgment.
func (s *PostgresStore) RecordFeedFeedbackEvent(ev FeedbackEvent) error {
	const q = `
INSERT INTO feedback_events (
    user_id, feed_id, kind, axis, axis_value, surface, exploration,
    feed_status, feed_errors)
SELECT $1, f.id, $3, NULLIF($4, ''), NULLIF($5, ''), $6, $7, f.status, f.consecutive_errors
FROM feeds f WHERE f.id = $2`
	_, err := s.pool.Exec(context.Background(), q,
		ev.UserID, ev.FeedID, string(ev.Kind), ev.Axis, ev.AxisValue,
		string(ev.Surface), ev.Exploration)
	if err != nil {
		return fmt.Errorf("record feed feedback %q for user %d: %w", ev.Kind, ev.UserID, err)
	}
	return nil
}

// ListFeedbackEvents returns a user's events, newest first. Intended for the
// corpus consumers and for tests; there is no UI for it.
func (s *PostgresStore) ListFeedbackEvents(userID int64, limit int) ([]FeedbackEventRow, error) {
	if limit <= 0 {
		limit = 100
	}
	const q = `
SELECT id, user_id, article_id, feed_id, article_title, article_url, kind,
       axis, axis_value, interest_score, score_model, prompt_hash, rules_fired,
       list_position, surface, exploration, feed_status, feed_errors,
       content_length, has_full_text, created_at, embedding IS NOT NULL
FROM feedback_events
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2`
	rows, err := s.pool.Query(context.Background(), q, userID, limit)
	if err != nil {
		return nil, fmt.Errorf("list feedback events for user %d: %w", userID, err)
	}
	defer rows.Close()

	var out []FeedbackEventRow
	for rows.Next() {
		var r FeedbackEventRow
		if err := rows.Scan(&r.ID, &r.UserID, &r.ArticleID, &r.FeedID, &r.ArticleTitle,
			&r.ArticleURL, &r.Kind, &r.Axis, &r.AxisValue, &r.InterestScore,
			&r.ScoreModel, &r.PromptHash, &r.RulesFired, &r.ListPosition, &r.Surface,
			&r.Exploration, &r.FeedStatus, &r.FeedErrors, &r.ContentLength,
			&r.HasFullText, &r.CreatedAt, &r.HasEmbedding); err != nil {
			return nil, fmt.Errorf("scan feedback event: %w", err)
		}
		out = append(out, r)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate feedback events for user %d: %w", userID, err)
	}
	return out, nil
}

// GetFeedbackEmbedding returns the embedding copy snapshotted onto an event.
// The copy is what keeps a label usable after DeleteFeedArticlesBatch removes
// the article it referred to.
func (s *PostgresStore) GetFeedbackEmbedding(eventID int64) ([]float32, error) {
	const q = `SELECT embedding FROM feedback_events WHERE id = $1`
	var vec *pgvector.Vector
	if err := s.pool.QueryRow(context.Background(), q, eventID).Scan(&vec); err != nil {
		return nil, fmt.Errorf("get feedback embedding %d: %w", eventID, err)
	}
	if vec == nil {
		return nil, nil
	}
	return vec.Slice(), nil
}
