package storage

import (
	"context"
	"fmt"

	"github.com/pgvector/pgvector-go"

	"github.com/matthewjhunter/herald/internal/storage/db"
)

// This file holds the embedding queries that read or write the vector value
// itself, hand-written on the pgx pool rather than generated by sqlc (#186).
// sqlc does not model pgvector's vector type or its distance operators (<=>), so
// the grouping and similarity queries -- centroid match, leftover pairing,
// centroid recompute -- live here. The vector type is registered per pooled
// connection in pool.go, so pgvector.Vector binds and scans natively.

// StoreArticleEmbedding upserts a successful embedding vector for an article,
// resetting status to ok and clearing the retry bookkeeping. The vector must
// have EmbedDim components; a different length means the configured model does
// not match the vector(EmbedDim) column, which is rejected here so it fails
// loudly rather than at the database with an opaque dimension error.
func (s *PostgresStore) StoreArticleEmbedding(articleID int64, vec []float32, model string) error {
	if len(vec) != EmbedDim {
		return fmt.Errorf("store embedding for article %d: vector has %d dimensions, want %d (embedding model mismatch)", articleID, len(vec), EmbedDim)
	}
	const q = `
		INSERT INTO article_embeddings (article_id, embedding, embedding_model, status, attempts, error_message, last_attempted_at)
		VALUES ($1, $2, $3, $4, 0, NULL, NULL)
		ON CONFLICT (article_id) DO UPDATE
		SET embedding = EXCLUDED.embedding,
		    embedding_model = EXCLUDED.embedding_model,
		    status = $4,
		    attempts = 0,
		    error_message = NULL,
		    last_attempted_at = NULL,
		    created_at = NOW()`
	_, err := s.pool.Exec(context.Background(), q, articleID, pgvector.NewVector(vec), model, int16(EmbedStatusOK))
	if err != nil {
		return fmt.Errorf("store article embedding: %w", err)
	}
	return nil
}

// GetArticleEmbeddings returns the usable (status ok) embedding vectors for a
// user's subscribed feeds under the given model. Used by the embedding-drift
// diagnostic; the grouping pipeline never pulls raw vectors into Go.
func (s *PostgresStore) GetArticleEmbeddings(userID int64, model string) ([]ArticleEmbeddingRow, error) {
	const q = `
		SELECT ae.article_id, ae.embedding
		FROM article_embeddings ae
		JOIN articles a ON a.id = ae.article_id
		JOIN user_feeds uf ON a.feed_id = uf.feed_id
		WHERE uf.user_id = $1 AND ae.embedding_model = $2 AND ae.status = $3`
	rows, err := s.pool.Query(context.Background(), q, userID, model, int16(EmbedStatusOK))
	if err != nil {
		return nil, fmt.Errorf("get article embeddings: %w", err)
	}
	defer rows.Close()

	var out []ArticleEmbeddingRow
	for rows.Next() {
		var id int64
		var vec pgvector.Vector
		if err := rows.Scan(&id, &vec); err != nil {
			return nil, fmt.Errorf("scan article embedding: %w", err)
		}
		out = append(out, ArticleEmbeddingRow{ArticleID: id, Embedding: vec.Slice()})
	}
	return out, rows.Err()
}

// SemanticSearch is the hybrid-search semantic path as an in-database query
// (#192): it returns the user's subscribed-feed articles whose embedding under
// model is within maxDist cosine distance of queryVec, nearest first, up to
// limit. It replaces the old fetch-every-embedding-and-cosine-in-Go scan -- the
// distance, ordering, and top-N now happen in Postgres, so only the hits cross
// into the app.
//
// This is an EXACT scan, not an ANN index lookup. Semantic search filters to a
// user's subscribed feeds with a JOIN to user_feeds, which pgvector's HNSW
// iterative scan cannot see (it compensates only for filters evaluated inside
// the index scan, not a join above it), so an HNSW index over the shared
// article_embeddings table would silently under-return whenever another user's
// articles are globally nearer to the query. An exact sequential scan ordered by
// distance is always correct, has no recall loss, and at herald's scale (a
// per-user article set in the thousands to low tens of thousands) runs in tens
// of milliseconds -- fine for an interactive, low-QPS search. queryVec must have
// EmbedDim components, matching the vector(EmbedDim) column.
func (s *PostgresStore) SemanticSearch(userID int64, model string, queryVec []float32, maxDist float64, limit int) ([]SemanticHit, error) {
	if len(queryVec) != EmbedDim {
		return nil, fmt.Errorf("semantic search: query vector has %d dimensions, want %d (embedding model mismatch)", len(queryVec), EmbedDim)
	}
	if limit <= 0 {
		return nil, nil
	}
	const q = `
		SELECT ae.article_id, ae.embedding <=> $1 AS distance
		FROM article_embeddings ae
		JOIN articles a ON a.id = ae.article_id
		JOIN user_feeds uf ON a.feed_id = uf.feed_id
		WHERE uf.user_id = $2 AND ae.embedding_model = $3 AND ae.status = $4
		  AND (ae.embedding <=> $1) < $5
		ORDER BY ae.embedding <=> $1
		LIMIT $6`
	rows, err := s.pool.Query(context.Background(), q, pgvector.NewVector(queryVec), userID, model, int16(EmbedStatusOK), maxDist, limit)
	if err != nil {
		return nil, fmt.Errorf("semantic search: %w", err)
	}
	defer rows.Close()

	var out []SemanticHit
	for rows.Next() {
		var h SemanticHit
		if err := rows.Scan(&h.ArticleID, &h.Distance); err != nil {
			return nil, fmt.Errorf("scan semantic hit: %w", err)
		}
		out = append(out, h)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

// MatchArticlesToGroups is the JOIN phase as an in-database ANN query: for each
// of the given articles that has a usable embedding under model, it finds the
// user's nearest existing group centroid within maxDist cosine distance (an
// HNSW index on article_groups.embedding backs the per-article search). It
// returns one GroupMatch per embedded article; GroupID is 0 when no group is
// near enough (a leftover). Articles with no usable embedding are absent.
func (s *PostgresStore) MatchArticlesToGroups(userID int64, model string, articleIDs []int64, maxDist float64) ([]GroupMatch, error) {
	if len(articleIDs) == 0 {
		return nil, nil
	}
	const q = `
		SELECT ae.article_id, COALESCE(g.group_id, 0)
		FROM article_embeddings ae
		LEFT JOIN LATERAL (
			SELECT ag.id AS group_id
			FROM article_groups ag
			WHERE ag.user_id = $1 AND ag.embedding IS NOT NULL AND ag.embedding_model = $2
			  AND (ag.embedding <=> ae.embedding) <= $4
			ORDER BY ag.embedding <=> ae.embedding
			LIMIT 1
		) g ON TRUE
		WHERE ae.article_id = ANY($3::bigint[]) AND ae.embedding_model = $2 AND ae.status = $5`
	rows, err := s.pool.Query(context.Background(), q, userID, model, articleIDs, maxDist, int16(EmbedStatusOK))
	if err != nil {
		return nil, fmt.Errorf("match articles to groups: %w", err)
	}
	defer rows.Close()

	var out []GroupMatch
	for rows.Next() {
		var m GroupMatch
		if err := rows.Scan(&m.ArticleID, &m.GroupID); err != nil {
			return nil, fmt.Errorf("scan group match: %w", err)
		}
		out = append(out, m)
	}
	return out, rows.Err()
}

// LeftoverSimilarPairs is the FORM phase's edge query: it returns every pair of
// the given articles (by id, low < high) whose embeddings are within maxDist
// cosine distance, under model and status ok. The caller runs single-linkage
// union-find over these edges. The article-id set is bounded (the recency
// window), so the all-pairs distance computation stays cheap and exact -- it
// links the same pairs the old in-Go cosine scan did, with no k-NN truncation.
func (s *PostgresStore) LeftoverSimilarPairs(model string, articleIDs []int64, maxDist float64) ([][2]int64, error) {
	if len(articleIDs) < 2 {
		return nil, nil
	}
	const q = `
		SELECT a.article_id, b.article_id
		FROM article_embeddings a
		JOIN article_embeddings b
		  ON b.article_id > a.article_id AND b.embedding_model = $1 AND b.status = $3
		WHERE a.article_id = ANY($2::bigint[]) AND b.article_id = ANY($2::bigint[])
		  AND a.embedding_model = $1 AND a.status = $3
		  AND (a.embedding <=> b.embedding) <= $4`
	rows, err := s.pool.Query(context.Background(), q, model, articleIDs, int16(EmbedStatusOK), maxDist)
	if err != nil {
		return nil, fmt.Errorf("leftover similar pairs: %w", err)
	}
	defer rows.Close()

	var out [][2]int64
	for rows.Next() {
		var a, b int64
		if err := rows.Scan(&a, &b); err != nil {
			return nil, fmt.Errorf("scan leftover pair: %w", err)
		}
		out = append(out, [2]int64{a, b})
	}
	return out, rows.Err()
}

// RecomputeGroupCentroid sets a group's centroid to the component-wise mean of
// its members' usable embeddings under model, computed in the database with
// pgvector's AVG aggregate so no vectors cross into Go. When the group has no
// member with a usable embedding the average is NULL and the centroid is left
// unchanged, so an as-yet-unembedded group keeps whatever centroid it had (none)
// until its members embed -- the basis of the self-healing repair pass.
func (s *PostgresStore) RecomputeGroupCentroid(groupID int64, model string) error {
	const q = `
		UPDATE article_groups ag
		SET embedding = sub.centroid, embedding_model = $2
		FROM (
			SELECT AVG(ae.embedding)::vector AS centroid
			FROM article_group_members m
			JOIN article_embeddings ae ON ae.article_id = m.article_id
			WHERE m.group_id = $1 AND ae.embedding_model = $2 AND ae.status = $3
		) sub
		WHERE ag.id = $1 AND sub.centroid IS NOT NULL`
	_, err := s.pool.Exec(context.Background(), q, groupID, model, int16(EmbedStatusOK))
	if err != nil {
		return fmt.Errorf("recompute group centroid: %w", err)
	}
	return nil
}

// GroupsNeedingCentroid returns the user's groups whose centroid is missing or
// stale (built under a different model) but that have at least one usable-embed
// member, so a RecomputeGroupCentroid call will populate them. See the query in
// embedding.sql for why this drives the cluster stage's repair pass.
func (s *PostgresStore) GroupsNeedingCentroid(userID int64, model string) ([]int64, error) {
	ids, err := s.q.GroupsNeedingCentroid(context.Background(), db.GroupsNeedingCentroidParams{
		UserID:         userID,
		EmbeddingModel: model,
		Status:         int16(EmbedStatusOK),
	})
	if err != nil {
		return nil, fmt.Errorf("groups needing centroid: %w", err)
	}
	return ids, nil
}
