package storage

import (
	"context"
	"fmt"

	"github.com/pgvector/pgvector-go"

	"github.com/matthewjhunter/herald/internal/storage/db"
)

// This file holds the embedding queries that read or write the vector value
// itself, hand-written on the pgx pool rather than generated by sqlc (#186).
// sqlc does not model pgvector's vector type or its distance operators (<=>), so
// the grouping and similarity queries -- centroid match, leftover pairing,
// centroid recompute -- live here. The vector type is registered per pooled
// connection in pool.go, so pgvector.Vector binds and scans natively.

// StoreArticleEmbeddings replaces an article's chunk vectors under the given
// model and marks the article embedded: the chunk rows and the status row are
// written in one transaction, so "status is ok" and "chunk rows exist" are never
// observed apart. Passing no chunks is an error -- a successful embed always
// produces at least one vector, and the too-short and failed cases have their
// own status calls.
//
// Every vector must have EmbedDim components; a different length means the
// configured model does not match the vector(EmbedDim) column, which is rejected
// here so it fails loudly rather than at the database with an opaque dimension
// error.
func (s *PostgresStore) StoreArticleEmbeddings(articleID int64, chunks []EmbeddingChunk, model string) error {
	if len(chunks) == 0 {
		return fmt.Errorf("store embeddings for article %d: no chunks", articleID)
	}
	for i, c := range chunks {
		if len(c.Vector) != EmbedDim {
			return fmt.Errorf("store embeddings for article %d: chunk %d has %d dimensions, want %d (embedding model mismatch)", articleID, i, len(c.Vector), EmbedDim)
		}
	}

	ctx := context.Background()
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("store article embeddings: begin: %w", err)
	}
	defer tx.Rollback(ctx) //nolint:errcheck // no-op after Commit

	// Delete rather than upsert: a re-embed can produce fewer chunks than last
	// time (the article was edited, or the budget changed), and leftover
	// high-ordinal rows would be vectors of text that is no longer there.
	const del = `DELETE FROM article_embedding_chunks WHERE article_id = $1 AND embedding_model = $2`
	if _, err := tx.Exec(ctx, del, articleID, model); err != nil {
		return fmt.Errorf("store article embeddings: clear chunks: %w", err)
	}

	const ins = `
		INSERT INTO article_embedding_chunks (article_id, embedding_model, ordinal, embedding, start_byte, end_byte)
		VALUES ($1, $2, $3, $4, $5, $6)`
	for i, c := range chunks {
		if _, err := tx.Exec(ctx, ins, articleID, model, i, pgvector.NewVector(c.Vector), c.StartByte, c.EndByte); err != nil {
			return fmt.Errorf("store article embeddings: insert chunk %d: %w", i, err)
		}
	}

	const status = `
		INSERT INTO article_embeddings (article_id, embedding_model, status, attempts, error_message, last_attempted_at)
		VALUES ($1, $2, $3, 0, NULL, NULL)
		ON CONFLICT (article_id) DO UPDATE
		SET embedding_model = EXCLUDED.embedding_model,
		    status = $3,
		    attempts = 0,
		    error_message = NULL,
		    last_attempted_at = NULL,
		    created_at = NOW()`
	if _, err := tx.Exec(ctx, status, articleID, model, int16(EmbedStatusOK)); err != nil {
		return fmt.Errorf("store article embeddings: status: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("store article embeddings: commit: %w", err)
	}
	return nil
}

// GetArticleEmbeddings returns the stored chunk vectors for a user's subscribed
// feeds under the given model, one row per chunk, ordered by article then
// ordinal. Used by the embedding-drift diagnostic; the grouping pipeline never
// pulls raw vectors into Go.
func (s *PostgresStore) GetArticleEmbeddings(userID int64, model string) ([]ArticleEmbeddingRow, error) {
	const q = `
		SELECT c.article_id, c.ordinal, c.embedding
		FROM article_embedding_chunks c
		JOIN articles a ON a.id = c.article_id
		JOIN user_feeds uf ON a.feed_id = uf.feed_id
		WHERE uf.user_id = $1 AND c.embedding_model = $2
		ORDER BY c.article_id, c.ordinal`
	rows, err := s.pool.Query(context.Background(), q, userID, model)
	if err != nil {
		return nil, fmt.Errorf("get article embeddings: %w", err)
	}
	defer rows.Close()

	var out []ArticleEmbeddingRow
	for rows.Next() {
		var r ArticleEmbeddingRow
		var vec pgvector.Vector
		if err := rows.Scan(&r.ArticleID, &r.Ordinal, &vec); err != nil {
			return nil, fmt.Errorf("scan article embedding: %w", err)
		}
		r.Embedding = vec.Slice()
		out = append(out, r)
	}
	return out, rows.Err()
}

// SemanticSearch is the hybrid-search semantic path as an in-database query
// (#192): it returns the user's subscribed-feed articles whose embedding under
// model is within maxDist cosine distance of queryVec, nearest first, up to
// limit. It replaces the old fetch-every-embedding-and-cosine-in-Go scan -- the
// distance, ordering, and top-N now happen in Postgres, so only the hits cross
// into the app.
//
// This is an EXACT scan, not an ANN index lookup. Semantic search filters to a
// user's subscribed feeds with a JOIN to user_feeds, which pgvector's HNSW
// iterative scan cannot see (it compensates only for filters evaluated inside
// the index scan, not a join above it), so an HNSW index over the shared
// article_embeddings table would silently under-return whenever another user's
// articles are globally nearer to the query. An exact sequential scan ordered by
// distance is always correct, has no recall loss, and at herald's scale (a
// per-user article set in the thousands to low tens of thousands) runs in tens
// of milliseconds -- fine for an interactive, low-QPS search. queryVec must have
// EmbedDim components, matching the vector(EmbedDim) column.
func (s *PostgresStore) SemanticSearch(userID int64, model string, queryVec []float32, maxDist float64, limit int) ([]SemanticHit, error) {
	if len(queryVec) != EmbedDim {
		return nil, fmt.Errorf("semantic search: query vector has %d dimensions, want %d (embedding model mismatch)", len(queryVec), EmbedDim)
	}
	if limit <= 0 {
		return nil, nil
	}
	// An article is several chunks, so a query can hit the same article more
	// than once. DISTINCT ON keeps each article's nearest chunk and drops the
	// rest, which is both the right ranking (an article is as relevant as its
	// most relevant passage) and the right result count -- a caller asking for
	// 20 results wants 20 articles, not 20 chunks from three of them.
	const q = `
		SELECT article_id, distance FROM (
			SELECT DISTINCT ON (c.article_id) c.article_id, c.embedding <=> $1 AS distance
			FROM article_embedding_chunks c
			JOIN articles a ON a.id = c.article_id
			JOIN user_feeds uf ON a.feed_id = uf.feed_id
			WHERE uf.user_id = $2 AND c.embedding_model = $3
			  AND (c.embedding <=> $1) < $4
			ORDER BY c.article_id, c.embedding <=> $1
		) hits
		ORDER BY distance
		LIMIT $5`
	rows, err := s.pool.Query(context.Background(), q, pgvector.NewVector(queryVec), userID, model, maxDist, limit)
	if err != nil {
		return nil, fmt.Errorf("semantic search: %w", err)
	}
	defer rows.Close()

	var out []SemanticHit
	for rows.Next() {
		var h SemanticHit
		if err := rows.Scan(&h.ArticleID, &h.Distance); err != nil {
			return nil, fmt.Errorf("scan semantic hit: %w", err)
		}
		out = append(out, h)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

// MatchArticlesToGroups is the JOIN phase as an in-database ANN query: for each
// of the given articles that has a usable embedding under model, it finds the
// user's nearest existing group centroid within maxDist cosine distance (an
// HNSW index on article_groups.embedding backs the per-article search). It
// returns one GroupMatch per embedded article; GroupID is 0 when no group is
// near enough (a leftover). Articles with no usable embedding are absent.
func (s *PostgresStore) MatchArticlesToGroups(userID int64, model string, articleIDs []int64, maxDist float64) ([]GroupMatch, error) {
	if len(articleIDs) == 0 {
		return nil, nil
	}
	// Each chunk finds its own nearest centroid; the article takes the best of
	// them. DISTINCT ON with NULLS LAST picks the closest matching chunk, and
	// falls through to a no-match row only when no chunk matched anything -- so
	// every article with chunks still produces exactly one row, as before.
	const q = `
		SELECT article_id, COALESCE(group_id, 0) FROM (
			SELECT DISTINCT ON (c.article_id) c.article_id, g.group_id, g.dist
			FROM article_embedding_chunks c
			LEFT JOIN LATERAL (
				SELECT ag.id AS group_id, ag.embedding <=> c.embedding AS dist
				FROM article_groups ag
				WHERE ag.user_id = $1 AND ag.embedding IS NOT NULL AND ag.embedding_model = $2
				  AND (ag.embedding <=> c.embedding) <= $4
				ORDER BY ag.embedding <=> c.embedding
				LIMIT 1
			) g ON TRUE
			WHERE c.article_id = ANY($3::bigint[]) AND c.embedding_model = $2
			ORDER BY c.article_id, g.dist NULLS LAST
		) best`
	rows, err := s.pool.Query(context.Background(), q, userID, model, articleIDs, maxDist)
	if err != nil {
		return nil, fmt.Errorf("match articles to groups: %w", err)
	}
	defer rows.Close()

	var out []GroupMatch
	for rows.Next() {
		var m GroupMatch
		if err := rows.Scan(&m.ArticleID, &m.GroupID); err != nil {
			return nil, fmt.Errorf("scan group match: %w", err)
		}
		out = append(out, m)
	}
	return out, rows.Err()
}

// LeftoverSimilarPairs is the FORM phase's edge query: it returns every pair of
// the given articles (by id, low < high) whose embeddings are within maxDist
// cosine distance, under model and status ok. The caller runs single-linkage
// union-find over these edges. The article-id set is bounded (the recency
// window), so the all-pairs distance computation stays cheap and exact -- it
// links the same pairs the old in-Go cosine scan did, with no k-NN truncation.
func (s *PostgresStore) LeftoverSimilarPairs(model string, articleIDs []int64, maxDist float64) ([][2]int64, error) {
	if len(articleIDs) < 2 {
		return nil, nil
	}
	// Two articles are linked when any chunk of one is within maxDist of any
	// chunk of the other -- the article-level distance is the minimum over
	// chunk pairs. For a single-chunk article this is exactly what it was
	// before. For a long one it means a passage-level match is enough, which is
	// the point of chunking; it also makes linking more permissive, so a
	// too-loose threshold now chains groups through one shared paragraph.
	//
	// DISTINCT collapses the several chunk pairs a linked article pair
	// produces, so the caller's union-find still sees one edge.
	const q = `
		SELECT DISTINCT a.article_id, b.article_id
		FROM article_embedding_chunks a
		JOIN article_embedding_chunks b
		  ON b.article_id > a.article_id AND b.embedding_model = $1
		WHERE a.article_id = ANY($2::bigint[]) AND b.article_id = ANY($2::bigint[])
		  AND a.embedding_model = $1
		  AND (a.embedding <=> b.embedding) <= $3`
	rows, err := s.pool.Query(context.Background(), q, model, articleIDs, maxDist)
	if err != nil {
		return nil, fmt.Errorf("leftover similar pairs: %w", err)
	}
	defer rows.Close()

	var out [][2]int64
	for rows.Next() {
		var a, b int64
		if err := rows.Scan(&a, &b); err != nil {
			return nil, fmt.Errorf("scan leftover pair: %w", err)
		}
		out = append(out, [2]int64{a, b})
	}
	return out, rows.Err()
}

// RecomputeGroupCentroid sets a group's centroid to the component-wise mean of
// its members' usable embeddings under model, computed in the database with
// pgvector's AVG aggregate so no vectors cross into Go. When the group has no
// member with a usable embedding the average is NULL and the centroid is left
// unchanged, so an as-yet-unembedded group keeps whatever centroid it had (none)
// until its members embed -- the basis of the self-healing repair pass.
func (s *PostgresStore) RecomputeGroupCentroid(groupID int64, model string) error {
	// Averaged per article first, then across articles: a 12-chunk feature and a
	// 1-chunk newswire item are one member each, and a straight average over
	// every chunk row would let the long one pull the centroid twelve times as
	// hard.
	const q = `
		UPDATE article_groups ag
		SET embedding = sub.centroid, embedding_model = $2
		FROM (
			SELECT AVG(per_article.v)::vector AS centroid
			FROM (
				SELECT AVG(c.embedding)::vector AS v
				FROM article_group_members m
				JOIN article_embedding_chunks c
				  ON c.article_id = m.article_id AND c.embedding_model = $2
				WHERE m.group_id = $1
				GROUP BY m.article_id
			) per_article
		) sub
		WHERE ag.id = $1 AND sub.centroid IS NOT NULL`
	_, err := s.pool.Exec(context.Background(), q, groupID, model)
	if err != nil {
		return fmt.Errorf("recompute group centroid: %w", err)
	}
	return nil
}

// GroupsNeedingCentroid returns the user's groups whose centroid is missing or
// stale (built under a different model) but that have at least one usable-embed
// member, so a RecomputeGroupCentroid call will populate them. See the query in
// embedding.sql for why this drives the cluster stage's repair pass.
func (s *PostgresStore) GroupsNeedingCentroid(userID int64, model string) ([]int64, error) {
	ids, err := s.q.GroupsNeedingCentroid(context.Background(), db.GroupsNeedingCentroidParams{
		UserID:         userID,
		EmbeddingModel: model,
		Status:         int16(EmbedStatusOK),
	})
	if err != nil {
		return nil, fmt.Errorf("groups needing centroid: %w", err)
	}
	return ids, nil
}
