// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_summary.sql

package db

import (
	"context"
	"time"
)

const createAISummary = `-- name: CreateAISummary :one
INSERT INTO ai_summaries (user_id, newsletter_id, status, model, prompt)
VALUES ($1, $2, 'generating', $3, $4)
RETURNING id
`

type CreateAISummaryParams struct {
	UserID       int64
	NewsletterID *int64
	Model        string
	Prompt       string
}

func (q *Queries) CreateAISummary(ctx context.Context, arg CreateAISummaryParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAISummary,
		arg.UserID,
		arg.NewsletterID,
		arg.Model,
		arg.Prompt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAISummaries = `-- name: GetAISummaries :many
SELECT id, user_id, newsletter_id, status, model, prompt, headline, content_html, article_ids_json, article_count, input_tokens, output_tokens, error, created_at, generated_at FROM ai_summaries
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type GetAISummariesParams struct {
	UserID int64
	Lim    int32
}

func (q *Queries) GetAISummaries(ctx context.Context, arg GetAISummariesParams) ([]AiSummary, error) {
	rows, err := q.db.Query(ctx, getAISummaries, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiSummary{}
	for rows.Next() {
		var i AiSummary
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NewsletterID,
			&i.Status,
			&i.Model,
			&i.Prompt,
			&i.Headline,
			&i.ContentHtml,
			&i.ArticleIdsJson,
			&i.ArticleCount,
			&i.InputTokens,
			&i.OutputTokens,
			&i.Error,
			&i.CreatedAt,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAISummariesForNewsletter = `-- name: GetAISummariesForNewsletter :many
SELECT id, user_id, newsletter_id, status, model, prompt, headline, content_html, article_ids_json, article_count, input_tokens, output_tokens, error, created_at, generated_at FROM ai_summaries
WHERE user_id = $1 AND newsletter_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type GetAISummariesForNewsletterParams struct {
	UserID       int64
	NewsletterID *int64
	Lim          int32
}

func (q *Queries) GetAISummariesForNewsletter(ctx context.Context, arg GetAISummariesForNewsletterParams) ([]AiSummary, error) {
	rows, err := q.db.Query(ctx, getAISummariesForNewsletter, arg.UserID, arg.NewsletterID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiSummary{}
	for rows.Next() {
		var i AiSummary
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NewsletterID,
			&i.Status,
			&i.Model,
			&i.Prompt,
			&i.Headline,
			&i.ContentHtml,
			&i.ArticleIdsJson,
			&i.ArticleCount,
			&i.InputTokens,
			&i.OutputTokens,
			&i.Error,
			&i.CreatedAt,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAISummary = `-- name: GetAISummary :one
SELECT id, user_id, newsletter_id, status, model, prompt, headline, content_html, article_ids_json, article_count, input_tokens, output_tokens, error, created_at, generated_at FROM ai_summaries
WHERE user_id = $1 AND id = $2
`

type GetAISummaryParams struct {
	UserID int64
	ID     int64
}

func (q *Queries) GetAISummary(ctx context.Context, arg GetAISummaryParams) (AiSummary, error) {
	row := q.db.QueryRow(ctx, getAISummary, arg.UserID, arg.ID)
	var i AiSummary
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NewsletterID,
		&i.Status,
		&i.Model,
		&i.Prompt,
		&i.Headline,
		&i.ContentHtml,
		&i.ArticleIdsJson,
		&i.ArticleCount,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Error,
		&i.CreatedAt,
		&i.GeneratedAt,
	)
	return i, err
}

const getInProgressAISummary = `-- name: GetInProgressAISummary :one
SELECT id, user_id, newsletter_id, status, model, prompt, headline, content_html, article_ids_json, article_count, input_tokens, output_tokens, error, created_at, generated_at FROM ai_summaries
WHERE user_id = $1 AND status = 'generating'
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetInProgressAISummary(ctx context.Context, userID int64) (AiSummary, error) {
	row := q.db.QueryRow(ctx, getInProgressAISummary, userID)
	var i AiSummary
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NewsletterID,
		&i.Status,
		&i.Model,
		&i.Prompt,
		&i.Headline,
		&i.ContentHtml,
		&i.ArticleIdsJson,
		&i.ArticleCount,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Error,
		&i.CreatedAt,
		&i.GeneratedAt,
	)
	return i, err
}

const getLatestAISummary = `-- name: GetLatestAISummary :one
SELECT id, user_id, newsletter_id, status, model, prompt, headline, content_html, article_ids_json, article_count, input_tokens, output_tokens, error, created_at, generated_at FROM ai_summaries
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestAISummary(ctx context.Context, userID int64) (AiSummary, error) {
	row := q.db.QueryRow(ctx, getLatestAISummary, userID)
	var i AiSummary
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NewsletterID,
		&i.Status,
		&i.Model,
		&i.Prompt,
		&i.Headline,
		&i.ContentHtml,
		&i.ArticleIdsJson,
		&i.ArticleCount,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Error,
		&i.CreatedAt,
		&i.GeneratedAt,
	)
	return i, err
}

const getUnreadArticlesForSummary = `-- name: GetUnreadArticlesForSummary :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.content, a.summary,
       a.author, a.published_date, a.fetched_date
FROM articles a
JOIN user_feeds uf ON a.feed_id = uf.feed_id
JOIN read_state rs ON a.id = rs.article_id AND rs.user_id = uf.user_id
WHERE uf.user_id = $1
  AND rs.read = FALSE
  AND a.security_score >= $2::double precision
  AND rs.interest_score >= $3::double precision
ORDER BY COALESCE(a.published_date, a.fetched_date) DESC
LIMIT $4
`

type GetUnreadArticlesForSummaryParams struct {
	UserID      int64
	MinSecurity float64
	MinInterest float64
	Lim         int32
}

type GetUnreadArticlesForSummaryRow struct {
	ID            int64
	FeedID        int64
	Guid          string
	Title         string
	Url           string
	Content       *string
	Summary       *string
	Author        *string
	PublishedDate *time.Time
	FetchedDate   time.Time
}

func (q *Queries) GetUnreadArticlesForSummary(ctx context.Context, arg GetUnreadArticlesForSummaryParams) ([]GetUnreadArticlesForSummaryRow, error) {
	rows, err := q.db.Query(ctx, getUnreadArticlesForSummary,
		arg.UserID,
		arg.MinSecurity,
		arg.MinInterest,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnreadArticlesForSummaryRow{}
	for rows.Next() {
		var i GetUnreadArticlesForSummaryRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Content,
			&i.Summary,
			&i.Author,
			&i.PublishedDate,
			&i.FetchedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAISummaryDone = `-- name: UpdateAISummaryDone :exec
UPDATE ai_summaries
SET status = 'done',
    headline = $1,
    content_html = $2,
    article_ids_json = $3,
    article_count = $4,
    input_tokens = $5,
    output_tokens = $6,
    error = '',
    generated_at = $7::timestamptz
WHERE id = $8
`

type UpdateAISummaryDoneParams struct {
	Headline       string
	ContentHtml    string
	ArticleIdsJson string
	ArticleCount   int
	InputTokens    int
	OutputTokens   int
	GeneratedAt    time.Time
	ID             int64
}

func (q *Queries) UpdateAISummaryDone(ctx context.Context, arg UpdateAISummaryDoneParams) error {
	_, err := q.db.Exec(ctx, updateAISummaryDone,
		arg.Headline,
		arg.ContentHtml,
		arg.ArticleIdsJson,
		arg.ArticleCount,
		arg.InputTokens,
		arg.OutputTokens,
		arg.GeneratedAt,
		arg.ID,
	)
	return err
}

const updateAISummaryFailed = `-- name: UpdateAISummaryFailed :exec
UPDATE ai_summaries
SET status = 'failed', error = $1, generated_at = $2::timestamptz
WHERE id = $3
`

type UpdateAISummaryFailedParams struct {
	Error       string
	GeneratedAt time.Time
	ID          int64
}

func (q *Queries) UpdateAISummaryFailed(ctx context.Context, arg UpdateAISummaryFailedParams) error {
	_, err := q.db.Exec(ctx, updateAISummaryFailed, arg.Error, arg.GeneratedAt, arg.ID)
	return err
}
