// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: article.sql

package db

import (
	"context"
	"time"
)

const addArticle = `-- name: AddArticle :one
INSERT INTO articles (feed_id, guid, title, url, content, summary, author, published_date)
VALUES ($1, $2, $3, $4, $5::text, $6::text, $7::text, $8)
ON CONFLICT (feed_id, guid) DO NOTHING
RETURNING id
`

type AddArticleParams struct {
	FeedID        int64
	Guid          string
	Title         string
	Url           string
	Content       string
	Summary       string
	Author        string
	PublishedDate *time.Time
}

func (q *Queries) AddArticle(ctx context.Context, arg AddArticleParams) (int64, error) {
	row := q.db.QueryRow(ctx, addArticle,
		arg.FeedID,
		arg.Guid,
		arg.Title,
		arg.Url,
		arg.Content,
		arg.Summary,
		arg.Author,
		arg.PublishedDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findDuplicateArticle = `-- name: FindDuplicateArticle :one
SELECT id FROM articles
WHERE title = $1 AND published_date = $2
LIMIT 1
`

type FindDuplicateArticleParams struct {
	Title         string
	PublishedDate *time.Time
}

func (q *Queries) FindDuplicateArticle(ctx context.Context, arg FindDuplicateArticleParams) (int64, error) {
	row := q.db.QueryRow(ctx, findDuplicateArticle, arg.Title, arg.PublishedDate)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getArticle = `-- name: GetArticle :one
SELECT id, feed_id, guid, title, url, content, summary, author,
       published_date, fetched_date, linked_url, linked_content
FROM articles WHERE id = $1
`

type GetArticleRow struct {
	ID            int64
	FeedID        int64
	Guid          string
	Title         string
	Url           string
	Content       *string
	Summary       *string
	Author        *string
	PublishedDate *time.Time
	FetchedDate   time.Time
	LinkedUrl     string
	LinkedContent string
}

func (q *Queries) GetArticle(ctx context.Context, id int64) (GetArticleRow, error) {
	row := q.db.QueryRow(ctx, getArticle, id)
	var i GetArticleRow
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Guid,
		&i.Title,
		&i.Url,
		&i.Content,
		&i.Summary,
		&i.Author,
		&i.PublishedDate,
		&i.FetchedDate,
		&i.LinkedUrl,
		&i.LinkedContent,
	)
	return i, err
}

const getArticlesNeedingFullText = `-- name: GetArticlesNeedingFullText :many
SELECT id, feed_id, guid, title, url, content, summary, author,
       published_date, fetched_date
FROM articles
WHERE full_text_fetched = FALSE
ORDER BY fetched_date DESC
LIMIT $1
`

type GetArticlesNeedingFullTextRow struct {
	ID            int64
	FeedID        int64
	Guid          string
	Title         string
	Url           string
	Content       *string
	Summary       *string
	Author        *string
	PublishedDate *time.Time
	FetchedDate   time.Time
}

func (q *Queries) GetArticlesNeedingFullText(ctx context.Context, lim int32) ([]GetArticlesNeedingFullTextRow, error) {
	rows, err := q.db.Query(ctx, getArticlesNeedingFullText, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetArticlesNeedingFullTextRow{}
	for rows.Next() {
		var i GetArticlesNeedingFullTextRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Content,
			&i.Summary,
			&i.Author,
			&i.PublishedDate,
			&i.FetchedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScreenedArticleSample = `-- name: GetScreenedArticleSample :many
SELECT id, title, content, security_threat
FROM articles
WHERE security_screened_at IS NOT NULL AND content <> ''
ORDER BY RANDOM()
LIMIT $1
`

type GetScreenedArticleSampleRow struct {
	ID             int64
	Title          string
	Content        *string
	SecurityThreat *float64
}

// A random sample of already-screened articles that still have content, for the
// plan-012 score-comparison harness (herald screen-compare). Diagnostic only.
func (q *Queries) GetScreenedArticleSample(ctx context.Context, lim int32) ([]GetScreenedArticleSampleRow, error) {
	rows, err := q.db.Query(ctx, getScreenedArticleSample, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetScreenedArticleSampleRow{}
	for rows.Next() {
		var i GetScreenedArticleSampleRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.SecurityThreat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUngroupedEmbeddedArticles = `-- name: GetUngroupedEmbeddedArticles :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.content, a.summary,
       a.author, a.published_date, a.fetched_date
FROM articles a
JOIN user_feeds uf ON a.feed_id = uf.feed_id
JOIN article_embeddings ae ON ae.article_id = a.id
    AND ae.embedding_model = $1 AND ae.status = $2
WHERE uf.user_id = $3
  AND a.security_threat <= $4::double precision
  AND COALESCE(a.published_date, a.fetched_date) >= $5::timestamptz
  AND NOT EXISTS (
      SELECT 1 FROM article_group_members agm
      JOIN article_groups ag ON agm.group_id = ag.id
      WHERE agm.article_id = a.id AND ag.user_id = uf.user_id
  )
ORDER BY COALESCE(a.published_date, a.fetched_date) DESC
LIMIT $6
`

type GetUngroupedEmbeddedArticlesParams struct {
	Model             string
	Status            int16
	UserID            int64
	MaxSecurityThreat float64
	Since             time.Time
	Lim               int32
}

type GetUngroupedEmbeddedArticlesRow struct {
	ID            int64
	FeedID        int64
	Guid          string
	Title         string
	Url           string
	Content       *string
	Summary       *string
	Author        *string
	PublishedDate *time.Time
	FetchedDate   time.Time
}

func (q *Queries) GetUngroupedEmbeddedArticles(ctx context.Context, arg GetUngroupedEmbeddedArticlesParams) ([]GetUngroupedEmbeddedArticlesRow, error) {
	rows, err := q.db.Query(ctx, getUngroupedEmbeddedArticles,
		arg.Model,
		arg.Status,
		arg.UserID,
		arg.MaxSecurityThreat,
		arg.Since,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUngroupedEmbeddedArticlesRow{}
	for rows.Next() {
		var i GetUngroupedEmbeddedArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Content,
			&i.Summary,
			&i.Author,
			&i.PublishedDate,
			&i.FetchedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadArticles = `-- name: GetUnreadArticles :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.content, a.summary,
       a.author, a.published_date, a.fetched_date
FROM articles a
LEFT JOIN read_state rs ON a.id = rs.article_id
WHERE rs.article_id IS NULL OR rs.read = FALSE
ORDER BY a.published_date DESC
LIMIT $1
`

type GetUnreadArticlesRow struct {
	ID            int64
	FeedID        int64
	Guid          string
	Title         string
	Url           string
	Content       *string
	Summary       *string
	Author        *string
	PublishedDate *time.Time
	FetchedDate   time.Time
}

func (q *Queries) GetUnreadArticles(ctx context.Context, lim int32) ([]GetUnreadArticlesRow, error) {
	rows, err := q.db.Query(ctx, getUnreadArticles, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnreadArticlesRow{}
	for rows.Next() {
		var i GetUnreadArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Content,
			&i.Summary,
			&i.Author,
			&i.PublishedDate,
			&i.FetchedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnscoredArticleCount = `-- name: GetUnscoredArticleCount :one
SELECT COUNT(*)::int
FROM articles a
JOIN user_feeds uf ON a.feed_id = uf.feed_id
LEFT JOIN read_state rs ON a.id = rs.article_id AND rs.user_id = $1
WHERE uf.user_id = $1
  AND (
    (a.security_screened_at IS NULL AND a.security_attempts < 3)
    OR (a.security_threat <= 3.0 AND rs.interest_score IS NULL)
  )
`

func (q *Queries) GetUnscoredArticleCount(ctx context.Context, userID int64) (int, error) {
	row := q.db.QueryRow(ctx, getUnscoredArticleCount, userID)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const getUnscoredCurationArticles = `-- name: GetUnscoredCurationArticles :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.content, a.summary,
       a.author, a.published_date, a.fetched_date
FROM articles a
JOIN user_feeds uf ON a.feed_id = uf.feed_id
LEFT JOIN read_state rs ON a.id = rs.article_id AND rs.user_id = uf.user_id
WHERE uf.user_id = $1
  AND a.security_threat <= $2::double precision
  AND rs.interest_score IS NULL
ORDER BY a.published_date DESC
LIMIT $3
`

type GetUnscoredCurationArticlesParams struct {
	UserID            int64
	MaxSecurityThreat float64
	Lim               int32
}

type GetUnscoredCurationArticlesRow struct {
	ID            int64
	FeedID        int64
	Guid          string
	Title         string
	Url           string
	Content       *string
	Summary       *string
	Author        *string
	PublishedDate *time.Time
	FetchedDate   time.Time
}

func (q *Queries) GetUnscoredCurationArticles(ctx context.Context, arg GetUnscoredCurationArticlesParams) ([]GetUnscoredCurationArticlesRow, error) {
	rows, err := q.db.Query(ctx, getUnscoredCurationArticles, arg.UserID, arg.MaxSecurityThreat, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnscoredCurationArticlesRow{}
	for rows.Next() {
		var i GetUnscoredCurationArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Content,
			&i.Summary,
			&i.Author,
			&i.PublishedDate,
			&i.FetchedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnscreenedArticles = `-- name: GetUnscreenedArticles :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.content, a.summary,
       a.author, a.published_date, a.fetched_date
FROM articles a
WHERE a.security_screened_at IS NULL AND a.security_attempts < 3
ORDER BY a.published_date DESC
LIMIT $1
`

type GetUnscreenedArticlesRow struct {
	ID            int64
	FeedID        int64
	Guid          string
	Title         string
	Url           string
	Content       *string
	Summary       *string
	Author        *string
	PublishedDate *time.Time
	FetchedDate   time.Time
}

func (q *Queries) GetUnscreenedArticles(ctx context.Context, lim int32) ([]GetUnscreenedArticlesRow, error) {
	rows, err := q.db.Query(ctx, getUnscreenedArticles, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnscreenedArticlesRow{}
	for rows.Next() {
		var i GetUnscreenedArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Content,
			&i.Summary,
			&i.Author,
			&i.PublishedDate,
			&i.FetchedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnsummarizedArticleCount = `-- name: GetUnsummarizedArticleCount :one
SELECT COUNT(*)::int
FROM articles a
LEFT JOIN article_summaries asumm ON asumm.article_id = a.id
WHERE asumm.article_id IS NULL
`

func (q *Queries) GetUnsummarizedArticleCount(ctx context.Context) (int, error) {
	row := q.db.QueryRow(ctx, getUnsummarizedArticleCount)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const getUnsummarizedScoredArticles = `-- name: GetUnsummarizedScoredArticles :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.content, a.summary,
       a.author, a.published_date, a.fetched_date
FROM articles a
LEFT JOIN article_summaries asumm ON asumm.article_id = a.id
WHERE a.security_threat <= $1::double precision AND asumm.article_id IS NULL
ORDER BY a.published_date DESC
LIMIT $2
`

type GetUnsummarizedScoredArticlesParams struct {
	MaxSecurityThreat float64
	Lim               int32
}

type GetUnsummarizedScoredArticlesRow struct {
	ID            int64
	FeedID        int64
	Guid          string
	Title         string
	Url           string
	Content       *string
	Summary       *string
	Author        *string
	PublishedDate *time.Time
	FetchedDate   time.Time
}

func (q *Queries) GetUnsummarizedScoredArticles(ctx context.Context, arg GetUnsummarizedScoredArticlesParams) ([]GetUnsummarizedScoredArticlesRow, error) {
	rows, err := q.db.Query(ctx, getUnsummarizedScoredArticles, arg.MaxSecurityThreat, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnsummarizedScoredArticlesRow{}
	for rows.Next() {
		var i GetUnsummarizedScoredArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Content,
			&i.Summary,
			&i.Author,
			&i.PublishedDate,
			&i.FetchedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementArticleSecurityAttempts = `-- name: IncrementArticleSecurityAttempts :exec
UPDATE articles SET security_attempts = security_attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementArticleSecurityAttempts(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementArticleSecurityAttempts, id)
	return err
}

const markArticleFullTextFetched = `-- name: MarkArticleFullTextFetched :exec
UPDATE articles SET full_text_fetched = TRUE WHERE id = $1
`

func (q *Queries) MarkArticleFullTextFetched(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markArticleFullTextFetched, id)
	return err
}

const screenArticleSecurity = `-- name: ScreenArticleSecurity :exec
UPDATE articles
SET security_threat = $1::double precision,
    security_category = $2::text,
    security_verified = $3,
    security_flagged = $4,
    security_screened_at = NOW()
WHERE id = $5
`

type ScreenArticleSecurityParams struct {
	SecurityThreat   float64
	SecurityCategory string
	SecurityVerified *bool
	SecurityFlagged  bool
	ID               int64
}

func (q *Queries) ScreenArticleSecurity(ctx context.Context, arg ScreenArticleSecurityParams) error {
	_, err := q.db.Exec(ctx, screenArticleSecurity,
		arg.SecurityThreat,
		arg.SecurityCategory,
		arg.SecurityVerified,
		arg.SecurityFlagged,
		arg.ID,
	)
	return err
}

const setInterestScore = `-- name: SetInterestScore :exec
INSERT INTO read_state (user_id, article_id, read, interest_score, ai_scored)
VALUES ($1, $2, FALSE, $3::double precision, TRUE)
ON CONFLICT (user_id, article_id) DO UPDATE SET
  interest_score = excluded.interest_score,
  ai_scored = TRUE
`

type SetInterestScoreParams struct {
	UserID        int64
	ArticleID     int64
	InterestScore float64
}

func (q *Queries) SetInterestScore(ctx context.Context, arg SetInterestScoreParams) error {
	_, err := q.db.Exec(ctx, setInterestScore, arg.UserID, arg.ArticleID, arg.InterestScore)
	return err
}

const skipArticleSecurity = `-- name: SkipArticleSecurity :exec
UPDATE articles
SET security_screened_at = NOW()
WHERE id = $1
`

// Marks an article screened-but-skipped (screened_at set, threat left NULL). The
// skip reason is herald-authored, not attacker text, but the column that held it
// is gone (plan 012); screened_at + NULL threat already encodes the state.
func (q *Queries) SkipArticleSecurity(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, skipArticleSecurity, id)
	return err
}

const updateArticleContent = `-- name: UpdateArticleContent :exec
UPDATE articles SET content = $1::text WHERE id = $2
`

type UpdateArticleContentParams struct {
	Content string
	ID      int64
}

func (q *Queries) UpdateArticleContent(ctx context.Context, arg UpdateArticleContentParams) error {
	_, err := q.db.Exec(ctx, updateArticleContent, arg.Content, arg.ID)
	return err
}

const updateArticleLinkedContent = `-- name: UpdateArticleLinkedContent :exec
UPDATE articles SET linked_url = $1, linked_content = $2 WHERE id = $3
`

type UpdateArticleLinkedContentParams struct {
	LinkedUrl     string
	LinkedContent string
	ID            int64
}

func (q *Queries) UpdateArticleLinkedContent(ctx context.Context, arg UpdateArticleLinkedContentParams) error {
	_, err := q.db.Exec(ctx, updateArticleLinkedContent, arg.LinkedUrl, arg.LinkedContent, arg.ID)
	return err
}
