// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: article_summary.sql

package db

import (
	"context"
	"time"
)

const getArticleSummaries = `-- name: GetArticleSummaries :many
SELECT article_id, ai_summary
FROM article_summaries
WHERE article_id = ANY($1::bigint[])
  AND ai_summary <> ''
`

type GetArticleSummariesRow struct {
	ArticleID int64
	AiSummary string
}

func (q *Queries) GetArticleSummaries(ctx context.Context, articleIds []int64) ([]GetArticleSummariesRow, error) {
	rows, err := q.db.Query(ctx, getArticleSummaries, articleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetArticleSummariesRow{}
	for rows.Next() {
		var i GetArticleSummariesRow
		if err := rows.Scan(&i.ArticleID, &i.AiSummary); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArticleSummary = `-- name: GetArticleSummary :one
SELECT article_id, ai_summary, generated_at
FROM article_summaries
WHERE article_id = $1
`

type GetArticleSummaryRow struct {
	ArticleID   int64
	AiSummary   string
	GeneratedAt time.Time
}

func (q *Queries) GetArticleSummary(ctx context.Context, articleID int64) (GetArticleSummaryRow, error) {
	row := q.db.QueryRow(ctx, getArticleSummary, articleID)
	var i GetArticleSummaryRow
	err := row.Scan(&i.ArticleID, &i.AiSummary, &i.GeneratedAt)
	return i, err
}

const markSummarizationSkipped = `-- name: MarkSummarizationSkipped :exec
INSERT INTO article_summaries (article_id, ai_summary, skip_reason)
VALUES ($1, '', $2::text)
ON CONFLICT (article_id) DO UPDATE SET
  skip_reason = EXCLUDED.skip_reason,
  generated_at = NOW()
`

type MarkSummarizationSkippedParams struct {
	ArticleID  int64
	SkipReason string
}

func (q *Queries) MarkSummarizationSkipped(ctx context.Context, arg MarkSummarizationSkippedParams) error {
	_, err := q.db.Exec(ctx, markSummarizationSkipped, arg.ArticleID, arg.SkipReason)
	return err
}

const updateArticleAISummary = `-- name: UpdateArticleAISummary :exec
INSERT INTO article_summaries (article_id, ai_summary, skip_reason)
VALUES ($1, $2, NULL)
ON CONFLICT (article_id) DO UPDATE SET
  ai_summary = EXCLUDED.ai_summary,
  skip_reason = NULL,
  generated_at = NOW()
`

type UpdateArticleAISummaryParams struct {
	ArticleID int64
	AiSummary string
}

func (q *Queries) UpdateArticleAISummary(ctx context.Context, arg UpdateArticleAISummaryParams) error {
	_, err := q.db.Exec(ctx, updateArticleAISummary, arg.ArticleID, arg.AiSummary)
	return err
}
