// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: article_link.sql

package db

import (
	"context"
)

const addArticleLink = `-- name: AddArticleLink :exec
INSERT INTO article_links (article_id, url_norm)
VALUES ($1, $2)
ON CONFLICT (article_id, url_norm) DO NOTHING
`

type AddArticleLinkParams struct {
	ArticleID int64
	UrlNorm   string
}

func (q *Queries) AddArticleLink(ctx context.Context, arg AddArticleLinkParams) error {
	_, err := q.db.Exec(ctx, addArticleLink, arg.ArticleID, arg.UrlNorm)
	return err
}

const getArticlesNeedingLinkExtraction = `-- name: GetArticlesNeedingLinkExtraction :many
SELECT id, content, summary
FROM articles
WHERE links_extracted = FALSE
ORDER BY fetched_date DESC
LIMIT $1
`

type GetArticlesNeedingLinkExtractionRow struct {
	ID      int64
	Content *string
	Summary *string
}

// Articles whose outbound links haven't been parsed yet (new + backfill).
func (q *Queries) GetArticlesNeedingLinkExtraction(ctx context.Context, lim int32) ([]GetArticlesNeedingLinkExtractionRow, error) {
	rows, err := q.db.Query(ctx, getArticlesNeedingLinkExtraction, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetArticlesNeedingLinkExtractionRow{}
	for rows.Next() {
		var i GetArticlesNeedingLinkExtractionRow
		if err := rows.Scan(&i.ID, &i.Content, &i.Summary); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markArticleLinksExtracted = `-- name: MarkArticleLinksExtracted :exec
UPDATE articles SET links_extracted = TRUE WHERE id = $1
`

func (q *Queries) MarkArticleLinksExtracted(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markArticleLinksExtracted, id)
	return err
}
