// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backlink.sql

package db

import (
	"context"
	"time"
)

const getArticleBacklinks = `-- name: GetArticleBacklinks :many
SELECT DISTINCT a.id, a.title, a.url,
       COALESCE(uf.user_title, f.title) AS feed_title,
       a.published_date, a.fetched_date
FROM article_links al
JOIN articles a ON a.id = al.article_id
JOIN feeds f ON f.id = a.feed_id
JOIN user_feeds uf ON uf.feed_id = a.feed_id AND uf.user_id = $1
WHERE starts_with(al.url_norm, $2::text)
  AND a.id <> $3
ORDER BY a.published_date DESC NULLS LAST, a.fetched_date DESC
LIMIT $4
`

type GetArticleBacklinksParams struct {
	UserID    int64
	Prefix    string
	ExcludeID int64
	Lim       int32
}

type GetArticleBacklinksRow struct {
	ID            int64
	Title         string
	Url           string
	FeedTitle     string
	PublishedDate *time.Time
	FetchedDate   time.Time
}

// "Which of my feeds linked to this?" -- articles in the user's subscribed
// feeds with an outbound link (parsed from body/summary into article_links)
// whose normalized form starts with @prefix. It's a prefix match, so a bare
// domain ("example.com") finds every link under it and a full URL finds that
// page; both sides are lower-cased and stripped (urlnorm), so matching is
// case-insensitive and ignores scheme/www/query/fragment/trailing-slash. The
// target article itself is excluded.
func (q *Queries) GetArticleBacklinks(ctx context.Context, arg GetArticleBacklinksParams) ([]GetArticleBacklinksRow, error) {
	rows, err := q.db.Query(ctx, getArticleBacklinks,
		arg.UserID,
		arg.Prefix,
		arg.ExcludeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetArticleBacklinksRow{}
	for rows.Next() {
		var i GetArticleBacklinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.FeedTitle,
			&i.PublishedDate,
			&i.FetchedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
