// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: embedding.sql

package db

import (
	"context"
	"time"
)

const getArticlesWithoutEmbeddings = `-- name: GetArticlesWithoutEmbeddings :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.content, a.summary,
       a.author, a.published_date, a.fetched_date
FROM articles a
LEFT JOIN article_embeddings ae ON a.id = ae.article_id AND ae.embedding_model = $1
WHERE ae.article_id IS NULL
   OR (ae.status = $2 AND ae.attempts < $3::int
       AND (ae.last_attempted_at IS NULL OR ae.last_attempted_at < $4::timestamptz))
ORDER BY a.published_date DESC
LIMIT $5
`

type GetArticlesWithoutEmbeddingsParams struct {
	EmbeddingModel string
	Status         int16
	MaxAttempts    int
	Cutoff         time.Time
	Lim            int32
}

type GetArticlesWithoutEmbeddingsRow struct {
	ID            int64
	FeedID        int64
	Guid          string
	Title         string
	Url           string
	Content       *string
	Summary       *string
	Author        *string
	PublishedDate *time.Time
	FetchedDate   time.Time
}

func (q *Queries) GetArticlesWithoutEmbeddings(ctx context.Context, arg GetArticlesWithoutEmbeddingsParams) ([]GetArticlesWithoutEmbeddingsRow, error) {
	rows, err := q.db.Query(ctx, getArticlesWithoutEmbeddings,
		arg.EmbeddingModel,
		arg.Status,
		arg.MaxAttempts,
		arg.Cutoff,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetArticlesWithoutEmbeddingsRow{}
	for rows.Next() {
		var i GetArticlesWithoutEmbeddingsRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Content,
			&i.Summary,
			&i.Author,
			&i.PublishedDate,
			&i.FetchedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupsNeedingCentroid = `-- name: GroupsNeedingCentroid :many
SELECT DISTINCT ag.id
FROM article_groups ag
JOIN article_group_members m ON m.group_id = ag.id
JOIN article_embeddings ae ON ae.article_id = m.article_id
  AND ae.embedding_model = $1 AND ae.status = $2
WHERE ag.user_id = $3
  AND (ag.embedding IS NULL OR ag.embedding_model <> $1)
`

type GroupsNeedingCentroidParams struct {
	EmbeddingModel string
	Status         int16
	UserID         int64
}

// Groups whose centroid is missing or was built under a different embedding
// model, but that have at least one member with a usable (status ok) embedding
// under the current model -- so a centroid recompute will actually produce a
// vector. Drives the cluster stage's self-healing centroid-repair pass (#186):
// after the BYTEA->vector reset (and after any model switch) existing groups
// have no centroid until their members re-embed.
func (q *Queries) GroupsNeedingCentroid(ctx context.Context, arg GroupsNeedingCentroidParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, groupsNeedingCentroid, arg.EmbeddingModel, arg.Status, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markArticleEmbeddingFailed = `-- name: MarkArticleEmbeddingFailed :exec
INSERT INTO article_embeddings (article_id, embedding_model, status, attempts, error_message, last_attempted_at)
VALUES ($1, $2, $3, 1, $4::text, NOW())
ON CONFLICT (article_id) DO UPDATE
SET embedding = NULL,
    embedding_model = EXCLUDED.embedding_model,
    status = $3,
    attempts = article_embeddings.attempts + 1,
    error_message = EXCLUDED.error_message,
    last_attempted_at = NOW(),
    created_at = NOW()
`

type MarkArticleEmbeddingFailedParams struct {
	ArticleID      int64
	EmbeddingModel string
	Status         int16
	ErrorMessage   string
}

func (q *Queries) MarkArticleEmbeddingFailed(ctx context.Context, arg MarkArticleEmbeddingFailedParams) error {
	_, err := q.db.Exec(ctx, markArticleEmbeddingFailed,
		arg.ArticleID,
		arg.EmbeddingModel,
		arg.Status,
		arg.ErrorMessage,
	)
	return err
}

const markArticleEmbeddingSkipped = `-- name: MarkArticleEmbeddingSkipped :exec

INSERT INTO article_embeddings (article_id, embedding_model, status, attempts, error_message, last_attempted_at)
VALUES ($1, $2, $3, 0, NULL, NULL)
ON CONFLICT (article_id) DO UPDATE
SET embedding = NULL,
    embedding_model = EXCLUDED.embedding_model,
    status = $3,
    attempts = 0,
    error_message = NULL,
    last_attempted_at = NULL,
    created_at = NOW()
`

type MarkArticleEmbeddingSkippedParams struct {
	ArticleID      int64
	EmbeddingModel string
	Status         int16
}

// Queries that read or write the embedding vector itself live in the
// hand-written pgvector layer (internal/storage/vector.go), not here: sqlc does
// not model the vector type or its distance operators (#186). This file holds
// the embedding bookkeeping queries -- status, retries, resets -- that never
// touch the vector value.
func (q *Queries) MarkArticleEmbeddingSkipped(ctx context.Context, arg MarkArticleEmbeddingSkippedParams) error {
	_, err := q.db.Exec(ctx, markArticleEmbeddingSkipped, arg.ArticleID, arg.EmbeddingModel, arg.Status)
	return err
}

const resetAllArticleEmbeddings = `-- name: ResetAllArticleEmbeddings :execrows
DELETE FROM article_embeddings
`

func (q *Queries) ResetAllArticleEmbeddings(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, resetAllArticleEmbeddings)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetAllGroupEmbeddings = `-- name: ResetAllGroupEmbeddings :execrows
UPDATE article_groups SET embedding = NULL, embedding_model = ''
`

func (q *Queries) ResetAllGroupEmbeddings(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, resetAllGroupEmbeddings)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetStuckEmbeddings = `-- name: ResetStuckEmbeddings :execrows
UPDATE article_embeddings
SET attempts = 0, last_attempted_at = NULL, error_message = NULL
WHERE embedding_model = $1 AND status = $2 AND attempts >= $3::int
`

type ResetStuckEmbeddingsParams struct {
	EmbeddingModel string
	Status         int16
	MaxAttempts    int
}

func (q *Queries) ResetStuckEmbeddings(ctx context.Context, arg ResetStuckEmbeddingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetStuckEmbeddings, arg.EmbeddingModel, arg.Status, arg.MaxAttempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetStuckEmbeddingsLike = `-- name: ResetStuckEmbeddingsLike :execrows
UPDATE article_embeddings
SET attempts = 0, last_attempted_at = NULL, error_message = NULL
WHERE embedding_model = $1 AND status = $2 AND attempts >= $3::int
  AND error_message LIKE $4::text
`

type ResetStuckEmbeddingsLikeParams struct {
	EmbeddingModel string
	Status         int16
	MaxAttempts    int
	ErrorPattern   string
}

func (q *Queries) ResetStuckEmbeddingsLike(ctx context.Context, arg ResetStuckEmbeddingsLikeParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetStuckEmbeddingsLike,
		arg.EmbeddingModel,
		arg.Status,
		arg.MaxAttempts,
		arg.ErrorPattern,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
