// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed.sql

package db

import (
	"context"
	"time"
)

const addFeed = `-- name: AddFeed :one
INSERT INTO feeds (url, title, description)
VALUES ($1, $2, $3::text)
RETURNING id
`

type AddFeedParams struct {
	Url         string
	Title       string
	Description string
}

func (q *Queries) AddFeed(ctx context.Context, arg AddFeedParams) (int64, error) {
	row := q.db.QueryRow(ctx, addFeed, arg.Url, arg.Title, arg.Description)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getActiveFeedsToFetch = `-- name: GetActiveFeedsToFetch :many
SELECT id, url, title, description, site_url, last_fetched, last_error, etag, last_modified, enabled, created_at, consecutive_errors, next_fetch_at, status, favicon_failed_at, favicon_fail_kind FROM feeds
WHERE enabled = TRUE AND status = 'active'
  AND (next_fetch_at IS NULL OR next_fetch_at <= NOW())
`

func (q *Queries) GetActiveFeedsToFetch(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.Query(ctx, getActiveFeedsToFetch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.SiteUrl,
			&i.LastFetched,
			&i.LastError,
			&i.Etag,
			&i.LastModified,
			&i.Enabled,
			&i.CreatedAt,
			&i.ConsecutiveErrors,
			&i.NextFetchAt,
			&i.Status,
			&i.FaviconFailedAt,
			&i.FaviconFailKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeed = `-- name: GetFeed :one
SELECT id, url, title, description, site_url, last_fetched, last_error, etag, last_modified, enabled, created_at, consecutive_errors, next_fetch_at, status, favicon_failed_at, favicon_fail_kind FROM feeds WHERE id = $1
`

func (q *Queries) GetFeed(ctx context.Context, id int64) (Feed, error) {
	row := q.db.QueryRow(ctx, getFeed, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.SiteUrl,
		&i.LastFetched,
		&i.LastError,
		&i.Etag,
		&i.LastModified,
		&i.Enabled,
		&i.CreatedAt,
		&i.ConsecutiveErrors,
		&i.NextFetchAt,
		&i.Status,
		&i.FaviconFailedAt,
		&i.FaviconFailKind,
	)
	return i, err
}

const getFeedErrorState = `-- name: GetFeedErrorState :one
SELECT consecutive_errors, last_fetched FROM feeds WHERE id = $1
`

type GetFeedErrorStateRow struct {
	ConsecutiveErrors int64
	LastFetched       *time.Time
}

func (q *Queries) GetFeedErrorState(ctx context.Context, id int64) (GetFeedErrorStateRow, error) {
	row := q.db.QueryRow(ctx, getFeedErrorState, id)
	var i GetFeedErrorStateRow
	err := row.Scan(&i.ConsecutiveErrors, &i.LastFetched)
	return i, err
}

const getFeedRecentPublishDates = `-- name: GetFeedRecentPublishDates :many
SELECT published_date FROM articles
WHERE feed_id = $1 AND published_date IS NOT NULL
ORDER BY published_date DESC
LIMIT 11
`

func (q *Queries) GetFeedRecentPublishDates(ctx context.Context, feedID int64) ([]*time.Time, error) {
	rows, err := q.db.Query(ctx, getFeedRecentPublishDates, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*time.Time{}
	for rows.Next() {
		var published_date *time.Time
		if err := rows.Scan(&published_date); err != nil {
			return nil, err
		}
		items = append(items, published_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementFeedError = `-- name: IncrementFeedError :exec
UPDATE feeds
SET last_error = $1::text, consecutive_errors = consecutive_errors + 1
WHERE id = $2
`

type IncrementFeedErrorParams struct {
	LastError string
	ID        int64
}

func (q *Queries) IncrementFeedError(ctx context.Context, arg IncrementFeedErrorParams) error {
	_, err := q.db.Exec(ctx, incrementFeedError, arg.LastError, arg.ID)
	return err
}

const markFeedDead = `-- name: MarkFeedDead :exec
UPDATE feeds SET status = 'dead' WHERE id = $1
`

func (q *Queries) MarkFeedDead(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markFeedDead, id)
	return err
}

const markFeedFetched = `-- name: MarkFeedFetched :exec
UPDATE feeds
SET last_fetched = NOW(), last_error = NULL, consecutive_errors = 0, status = 'active'
WHERE id = $1
`

func (q *Queries) MarkFeedFetched(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markFeedFetched, id)
	return err
}

const markFeedFetchedWithNext = `-- name: MarkFeedFetchedWithNext :exec
UPDATE feeds
SET last_fetched = NOW(), last_error = NULL, consecutive_errors = 0,
    status = 'active', next_fetch_at = $1
WHERE id = $2
`

type MarkFeedFetchedWithNextParams struct {
	NextFetchAt *time.Time
	ID          int64
}

func (q *Queries) MarkFeedFetchedWithNext(ctx context.Context, arg MarkFeedFetchedWithNextParams) error {
	_, err := q.db.Exec(ctx, markFeedFetchedWithNext, arg.NextFetchAt, arg.ID)
	return err
}

const renameFeed = `-- name: RenameFeed :exec
UPDATE feeds SET title = $1 WHERE id = $2
`

type RenameFeedParams struct {
	Title string
	ID    int64
}

func (q *Queries) RenameFeed(ctx context.Context, arg RenameFeedParams) error {
	_, err := q.db.Exec(ctx, renameFeed, arg.Title, arg.ID)
	return err
}

const renameUserFeed = `-- name: RenameUserFeed :exec
UPDATE user_feeds SET user_title = $1 WHERE user_id = $2 AND feed_id = $3
`

type RenameUserFeedParams struct {
	UserTitle *string
	UserID    int64
	FeedID    int64
}

func (q *Queries) RenameUserFeed(ctx context.Context, arg RenameUserFeedParams) error {
	_, err := q.db.Exec(ctx, renameUserFeed, arg.UserTitle, arg.UserID, arg.FeedID)
	return err
}

const setFeedNextFetch = `-- name: SetFeedNextFetch :exec
UPDATE feeds SET next_fetch_at = $1 WHERE id = $2
`

type SetFeedNextFetchParams struct {
	NextFetchAt *time.Time
	ID          int64
}

func (q *Queries) SetFeedNextFetch(ctx context.Context, arg SetFeedNextFetchParams) error {
	_, err := q.db.Exec(ctx, setFeedNextFetch, arg.NextFetchAt, arg.ID)
	return err
}

const updateFeedCacheHeaders = `-- name: UpdateFeedCacheHeaders :exec
UPDATE feeds SET etag = $1::text, last_modified = $2::text WHERE id = $3
`

type UpdateFeedCacheHeadersParams struct {
	Etag         string
	LastModified string
	ID           int64
}

func (q *Queries) UpdateFeedCacheHeaders(ctx context.Context, arg UpdateFeedCacheHeadersParams) error {
	_, err := q.db.Exec(ctx, updateFeedCacheHeaders, arg.Etag, arg.LastModified, arg.ID)
	return err
}

const updateFeedSiteURL = `-- name: UpdateFeedSiteURL :exec
UPDATE feeds SET site_url = $1 WHERE id = $2
`

type UpdateFeedSiteURLParams struct {
	SiteUrl string
	ID      int64
}

func (q *Queries) UpdateFeedSiteURL(ctx context.Context, arg UpdateFeedSiteURLParams) error {
	_, err := q.db.Exec(ctx, updateFeedSiteURL, arg.SiteUrl, arg.ID)
	return err
}
