// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_tag.sql

package db

import (
	"context"
)

const addFeedTag = `-- name: AddFeedTag :exec
INSERT INTO feed_tags (user_id, feed_id, tag)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddFeedTagParams struct {
	UserID int64
	FeedID int64
	Tag    string
}

func (q *Queries) AddFeedTag(ctx context.Context, arg AddFeedTagParams) error {
	_, err := q.db.Exec(ctx, addFeedTag, arg.UserID, arg.FeedID, arg.Tag)
	return err
}

const getAllFeedTags = `-- name: GetAllFeedTags :many
SELECT feed_id, tag FROM feed_tags
WHERE user_id = $1
ORDER BY feed_id, tag
`

type GetAllFeedTagsRow struct {
	FeedID int64
	Tag    string
}

func (q *Queries) GetAllFeedTags(ctx context.Context, userID int64) ([]GetAllFeedTagsRow, error) {
	rows, err := q.db.Query(ctx, getAllFeedTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllFeedTagsRow{}
	for rows.Next() {
		var i GetAllFeedTagsRow
		if err := rows.Scan(&i.FeedID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedTags = `-- name: GetFeedTags :many
SELECT tag FROM feed_tags
WHERE user_id = $1 AND feed_id = $2
ORDER BY tag
`

type GetFeedTagsParams struct {
	UserID int64
	FeedID int64
}

func (q *Queries) GetFeedTags(ctx context.Context, arg GetFeedTagsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getFeedTags, arg.UserID, arg.FeedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedsByTags = `-- name: GetFeedsByTags :many
SELECT DISTINCT feed_id FROM feed_tags
WHERE user_id = $1 AND lower(tag) = ANY($2::text[])
ORDER BY feed_id
`

type GetFeedsByTagsParams struct {
	UserID int64
	Tags   []string
}

// Tags must be lower-cased by the caller; matched case-insensitively.
func (q *Queries) GetFeedsByTags(ctx context.Context, arg GetFeedsByTagsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, getFeedsByTags, arg.UserID, arg.Tags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var feed_id int64
		if err := rows.Scan(&feed_id); err != nil {
			return nil, err
		}
		items = append(items, feed_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTags = `-- name: GetUserTags :many
SELECT DISTINCT tag FROM feed_tags
WHERE user_id = $1
ORDER BY tag
`

func (q *Queries) GetUserTags(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFeedTag = `-- name: RemoveFeedTag :exec
DELETE FROM feed_tags
WHERE user_id = $1 AND feed_id = $2 AND lower(tag) = lower($3)
`

type RemoveFeedTagParams struct {
	UserID int64
	FeedID int64
	Tag    string
}

func (q *Queries) RemoveFeedTag(ctx context.Context, arg RemoveFeedTagParams) error {
	_, err := q.db.Exec(ctx, removeFeedTag, arg.UserID, arg.FeedID, arg.Tag)
	return err
}
