// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fever.sql

package db

import (
	"context"
	"time"
)

const deleteFeverCredential = `-- name: DeleteFeverCredential :exec
DELETE FROM fever_credentials WHERE user_id = $1
`

func (q *Queries) DeleteFeverCredential(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteFeverCredential, userID)
	return err
}

const getFeedGroupMemberships = `-- name: GetFeedGroupMemberships :many
SELECT agm.group_id, a.feed_id
FROM article_group_members agm
JOIN articles a ON a.id = agm.article_id
JOIN article_groups ag ON ag.id = agm.group_id
WHERE ag.user_id = $1
GROUP BY agm.group_id, a.feed_id
ORDER BY agm.group_id, a.feed_id
`

type GetFeedGroupMembershipsRow struct {
	GroupID int64
	FeedID  int64
}

func (q *Queries) GetFeedGroupMemberships(ctx context.Context, userID int64) ([]GetFeedGroupMembershipsRow, error) {
	rows, err := q.db.Query(ctx, getFeedGroupMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFeedGroupMembershipsRow{}
	for rows.Next() {
		var i GetFeedGroupMembershipsRow
		if err := rows.Scan(&i.GroupID, &i.FeedID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeverAPIKey = `-- name: GetFeverAPIKey :one
SELECT api_key FROM fever_credentials WHERE user_id = $1
`

func (q *Queries) GetFeverAPIKey(ctx context.Context, userID int64) (string, error) {
	row := q.db.QueryRow(ctx, getFeverAPIKey, userID)
	var api_key string
	err := row.Scan(&api_key)
	return api_key, err
}

const getFeverItemCount = `-- name: GetFeverItemCount :one
SELECT COUNT(*)::int
FROM articles a
JOIN user_feeds uf ON uf.feed_id = a.feed_id AND uf.user_id = $1
`

func (q *Queries) GetFeverItemCount(ctx context.Context, userID int64) (int, error) {
	row := q.db.QueryRow(ctx, getFeverItemCount, userID)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const getFeverItemsByIDs = `-- name: GetFeverItemsByIDs :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.content, a.summary,
       a.author, a.published_date, a.fetched_date,
       COALESCE(rs.read, FALSE) AS is_read,
       COALESCE(rs.starred, FALSE) AS is_starred
FROM articles a
JOIN user_feeds uf ON uf.feed_id = a.feed_id AND uf.user_id = $1
LEFT JOIN read_state rs ON rs.article_id = a.id AND rs.user_id = $1
WHERE a.id = ANY($2::bigint[])
ORDER BY a.id DESC LIMIT $3
`

type GetFeverItemsByIDsParams struct {
	UserID     int64
	ArticleIds []int64
	Lim        int32
}

type GetFeverItemsByIDsRow struct {
	ID            int64
	FeedID        int64
	Guid          string
	Title         string
	Url           string
	Content       *string
	Summary       *string
	Author        *string
	PublishedDate *time.Time
	FetchedDate   time.Time
	IsRead        bool
	IsStarred     bool
}

func (q *Queries) GetFeverItemsByIDs(ctx context.Context, arg GetFeverItemsByIDsParams) ([]GetFeverItemsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getFeverItemsByIDs, arg.UserID, arg.ArticleIds, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFeverItemsByIDsRow{}
	for rows.Next() {
		var i GetFeverItemsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Content,
			&i.Summary,
			&i.Author,
			&i.PublishedDate,
			&i.FetchedDate,
			&i.IsRead,
			&i.IsStarred,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeverItemsRange = `-- name: GetFeverItemsRange :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.content, a.summary,
       a.author, a.published_date, a.fetched_date,
       COALESCE(rs.read, FALSE) AS is_read,
       COALESCE(rs.starred, FALSE) AS is_starred
FROM articles a
JOIN user_feeds uf ON uf.feed_id = a.feed_id AND uf.user_id = $1
LEFT JOIN read_state rs ON rs.article_id = a.id AND rs.user_id = $1
WHERE ($2::bigint = 0 OR a.id > $2::bigint)
  AND ($3::bigint = 0 OR a.id <= $3::bigint)
ORDER BY a.id DESC LIMIT $4
`

type GetFeverItemsRangeParams struct {
	UserID  int64
	SinceID int64
	MaxID   int64
	Lim     int32
}

type GetFeverItemsRangeRow struct {
	ID            int64
	FeedID        int64
	Guid          string
	Title         string
	Url           string
	Content       *string
	Summary       *string
	Author        *string
	PublishedDate *time.Time
	FetchedDate   time.Time
	IsRead        bool
	IsStarred     bool
}

// since_id / max_id of 0 disable that bound (the Fever API's default).
func (q *Queries) GetFeverItemsRange(ctx context.Context, arg GetFeverItemsRangeParams) ([]GetFeverItemsRangeRow, error) {
	rows, err := q.db.Query(ctx, getFeverItemsRange,
		arg.UserID,
		arg.SinceID,
		arg.MaxID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFeverItemsRangeRow{}
	for rows.Next() {
		var i GetFeverItemsRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Content,
			&i.Summary,
			&i.Author,
			&i.PublishedDate,
			&i.FetchedDate,
			&i.IsRead,
			&i.IsStarred,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeverLinks = `-- name: GetFeverLinks :many
SELECT
    ag.id AS group_id,
    agm.article_id,
    a.feed_id,
    a.title,
    a.url,
    (CASE WHEN COALESCE(rs.starred, FALSE) THEN 1 ELSE 0 END)::int AS is_saved,
    COALESCE(gs.max_interest_score, 0)::double precision AS score
FROM article_groups ag
JOIN article_group_members agm ON agm.group_id = ag.id
JOIN articles a ON a.id = agm.article_id
LEFT JOIN read_state rs ON rs.article_id = a.id AND rs.user_id = $1
LEFT JOIN group_summaries gs ON gs.group_id = ag.id
WHERE ag.user_id = $1
ORDER BY ag.updated_at DESC, agm.added_at ASC
`

type GetFeverLinksRow struct {
	GroupID   int64
	ArticleID int64
	FeedID    int64
	Title     string
	Url       string
	IsSaved   int
	Score     float64
}

func (q *Queries) GetFeverLinks(ctx context.Context, userID int64) ([]GetFeverLinksRow, error) {
	rows, err := q.db.Query(ctx, getFeverLinks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFeverLinksRow{}
	for rows.Next() {
		var i GetFeverLinksRow
		if err := rows.Scan(
			&i.GroupID,
			&i.ArticleID,
			&i.FeedID,
			&i.Title,
			&i.Url,
			&i.IsSaved,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStarredArticleIDsForUser = `-- name: GetStarredArticleIDsForUser :many
SELECT article_id FROM read_state
WHERE user_id = $1 AND starred = TRUE
ORDER BY article_id
`

func (q *Queries) GetStarredArticleIDsForUser(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getStarredArticleIDsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var article_id int64
		if err := rows.Scan(&article_id); err != nil {
			return nil, err
		}
		items = append(items, article_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadArticleIDsForUser = `-- name: GetUnreadArticleIDsForUser :many
SELECT a.id
FROM articles a
JOIN user_feeds uf ON uf.feed_id = a.feed_id AND uf.user_id = $1
LEFT JOIN read_state rs ON rs.article_id = a.id AND rs.user_id = $1
WHERE NOT COALESCE(rs.read, FALSE)
ORDER BY a.id
`

func (q *Queries) GetUnreadArticleIDsForUser(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getUnreadArticleIDsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByFeverAPIKey = `-- name: GetUserByFeverAPIKey :one
SELECT u.id, u.name, u.oidc_sub, u.email, u.created_at FROM users u
JOIN fever_credentials fc ON fc.user_id = u.id
WHERE fc.api_key = $1
`

func (q *Queries) GetUserByFeverAPIKey(ctx context.Context, apiKey string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByFeverAPIKey, apiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OidcSub,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const markAllArticlesRead = `-- name: MarkAllArticlesRead :exec
INSERT INTO read_state (user_id, article_id, read, read_date)
SELECT $1, a.id, TRUE, NOW()
FROM articles a
JOIN user_feeds uf ON uf.feed_id = a.feed_id AND uf.user_id = $1
WHERE ($2::bool = FALSE OR a.published_date IS NULL OR a.published_date <= $3::timestamptz)
ON CONFLICT (user_id, article_id) DO UPDATE SET read = TRUE, read_date = NOW()
`

type MarkAllArticlesReadParams struct {
	UserID       int64
	FilterBefore bool
	Before       time.Time
}

func (q *Queries) MarkAllArticlesRead(ctx context.Context, arg MarkAllArticlesReadParams) error {
	_, err := q.db.Exec(ctx, markAllArticlesRead, arg.UserID, arg.FilterBefore, arg.Before)
	return err
}

const markFeedArticlesRead = `-- name: MarkFeedArticlesRead :exec
INSERT INTO read_state (user_id, article_id, read, read_date)
SELECT $1, a.id, TRUE, NOW()
FROM articles a
WHERE a.feed_id = $2
  AND ($3::bool = FALSE OR a.published_date IS NULL OR a.published_date <= $4::timestamptz)
ON CONFLICT (user_id, article_id) DO UPDATE SET read = TRUE, read_date = NOW()
`

type MarkFeedArticlesReadParams struct {
	UserID       int64
	FeedID       int64
	FilterBefore bool
	Before       time.Time
}

// filter_before = false marks every article; otherwise only those at or before
// @before (or with no publish date).
func (q *Queries) MarkFeedArticlesRead(ctx context.Context, arg MarkFeedArticlesReadParams) error {
	_, err := q.db.Exec(ctx, markFeedArticlesRead,
		arg.UserID,
		arg.FeedID,
		arg.FilterBefore,
		arg.Before,
	)
	return err
}

const markGroupArticlesRead = `-- name: MarkGroupArticlesRead :exec
INSERT INTO read_state (user_id, article_id, read, read_date)
SELECT $1, a.id, TRUE, NOW()
FROM articles a
JOIN article_group_members agm ON agm.article_id = a.id
WHERE agm.group_id = $2
  AND ($3::bool = FALSE OR a.published_date IS NULL OR a.published_date <= $4::timestamptz)
ON CONFLICT (user_id, article_id) DO UPDATE SET read = TRUE, read_date = NOW()
`

type MarkGroupArticlesReadParams struct {
	UserID       int64
	GroupID      int64
	FilterBefore bool
	Before       time.Time
}

func (q *Queries) MarkGroupArticlesRead(ctx context.Context, arg MarkGroupArticlesReadParams) error {
	_, err := q.db.Exec(ctx, markGroupArticlesRead,
		arg.UserID,
		arg.GroupID,
		arg.FilterBefore,
		arg.Before,
	)
	return err
}

const setFeverCredential = `-- name: SetFeverCredential :exec
INSERT INTO fever_credentials (user_id, api_key) VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET api_key = excluded.api_key
`

type SetFeverCredentialParams struct {
	UserID int64
	ApiKey string
}

func (q *Queries) SetFeverCredential(ctx context.Context, arg SetFeverCredentialParams) error {
	_, err := q.db.Exec(ctx, setFeverCredential, arg.UserID, arg.ApiKey)
	return err
}
