// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: filter.sql

package db

import (
	"context"
)

const addFilterRule = `-- name: AddFilterRule :one
INSERT INTO filter_rules (user_id, feed_id, axis, value, score)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type AddFilterRuleParams struct {
	UserID int64
	FeedID *int64
	Axis   string
	Value  string
	Score  int64
}

func (q *Queries) AddFilterRule(ctx context.Context, arg AddFilterRuleParams) (int64, error) {
	row := q.db.QueryRow(ctx, addFilterRule,
		arg.UserID,
		arg.FeedID,
		arg.Axis,
		arg.Value,
		arg.Score,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteFilterRule = `-- name: DeleteFilterRule :execrows
DELETE FROM filter_rules WHERE id = $1 AND user_id = $2
`

type DeleteFilterRuleParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteFilterRule(ctx context.Context, arg DeleteFilterRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFilterRule, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFilterRules = `-- name: GetFilterRules :many
SELECT id, user_id, feed_id, axis, value, score, created_at FROM filter_rules
WHERE user_id = $1
  AND ($2::bigint IS NULL OR feed_id IS NULL OR feed_id = $2)
ORDER BY axis, value
`

type GetFilterRulesParams struct {
	UserID int64
	FeedID *int64
}

// When feed_id is NULL the caller wants every rule for the user; when set, the
// user's global rules (feed_id IS NULL) plus rules scoped to that feed.
func (q *Queries) GetFilterRules(ctx context.Context, arg GetFilterRulesParams) ([]FilterRule, error) {
	rows, err := q.db.Query(ctx, getFilterRules, arg.UserID, arg.FeedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilterRule{}
	for rows.Next() {
		var i FilterRule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedID,
			&i.Axis,
			&i.Value,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasFilterRules = `-- name: HasFilterRules :one
SELECT COUNT(*) FROM filter_rules WHERE user_id = $1
`

func (q *Queries) HasFilterRules(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, hasFilterRules, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateFilterRuleScore = `-- name: UpdateFilterRuleScore :execrows
UPDATE filter_rules SET score = $1 WHERE id = $2 AND user_id = $3
`

type UpdateFilterRuleScoreParams struct {
	Score  int64
	ID     int64
	UserID int64
}

func (q *Queries) UpdateFilterRuleScore(ctx context.Context, arg UpdateFilterRuleScoreParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFilterRuleScore, arg.Score, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
