// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group.sql

package db

import (
	"context"
	"time"
)

const addArticleGroupMember = `-- name: AddArticleGroupMember :exec
INSERT INTO article_group_members (group_id, article_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddArticleGroupMemberParams struct {
	GroupID   int64
	ArticleID int64
}

func (q *Queries) AddArticleGroupMember(ctx context.Context, arg AddArticleGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addArticleGroupMember, arg.GroupID, arg.ArticleID)
	return err
}

const createArticleGroup = `-- name: CreateArticleGroup :one
INSERT INTO article_groups (user_id, topic) VALUES ($1, $2) RETURNING id
`

type CreateArticleGroupParams struct {
	UserID int64
	Topic  string
}

func (q *Queries) CreateArticleGroup(ctx context.Context, arg CreateArticleGroupParams) (int64, error) {
	row := q.db.QueryRow(ctx, createArticleGroup, arg.UserID, arg.Topic)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const disbandGroup = `-- name: DisbandGroup :exec
DELETE FROM article_groups WHERE id = $1
`

func (q *Queries) DisbandGroup(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, disbandGroup, id)
	return err
}

const findArticleGroup = `-- name: FindArticleGroup :one
SELECT agm.group_id FROM article_group_members agm
JOIN article_groups ag ON agm.group_id = ag.id
WHERE agm.article_id = $1 AND ag.user_id = $2
`

type FindArticleGroupParams struct {
	ArticleID int64
	UserID    int64
}

func (q *Queries) FindArticleGroup(ctx context.Context, arg FindArticleGroupParams) (int64, error) {
	row := q.db.QueryRow(ctx, findArticleGroup, arg.ArticleID, arg.UserID)
	var group_id int64
	err := row.Scan(&group_id)
	return group_id, err
}

const getArticleInterestScores = `-- name: GetArticleInterestScores :many
SELECT article_id, interest_score FROM read_state
WHERE user_id = $1
  AND article_id = ANY($2::bigint[])
  AND interest_score IS NOT NULL
`

type GetArticleInterestScoresParams struct {
	UserID     int64
	ArticleIds []int64
}

type GetArticleInterestScoresRow struct {
	ArticleID     int64
	InterestScore *float64
}

func (q *Queries) GetArticleInterestScores(ctx context.Context, arg GetArticleInterestScoresParams) ([]GetArticleInterestScoresRow, error) {
	rows, err := q.db.Query(ctx, getArticleInterestScores, arg.UserID, arg.ArticleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetArticleInterestScoresRow{}
	for rows.Next() {
		var i GetArticleInterestScoresRow
		if err := rows.Scan(&i.ArticleID, &i.InterestScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArticleSecurityScores = `-- name: GetArticleSecurityScores :many
SELECT id, security_score FROM articles
WHERE id = ANY($1::bigint[])
  AND security_score IS NOT NULL
`

type GetArticleSecurityScoresRow struct {
	ID            int64
	SecurityScore *float64
}

func (q *Queries) GetArticleSecurityScores(ctx context.Context, articleIds []int64) ([]GetArticleSecurityScoresRow, error) {
	rows, err := q.db.Query(ctx, getArticleSecurityScores, articleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetArticleSecurityScoresRow{}
	for rows.Next() {
		var i GetArticleSecurityScoresRow
		if err := rows.Scan(&i.ID, &i.SecurityScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroup = `-- name: GetGroup :one
SELECT id, user_id, topic, display_name, muted, created_at, updated_at
FROM article_groups WHERE id = $1
`

type GetGroupRow struct {
	ID          int64
	UserID      int64
	Topic       string
	DisplayName *string
	Muted       bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetGroup(ctx context.Context, id int64) (GetGroupRow, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i GetGroupRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Topic,
		&i.DisplayName,
		&i.Muted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupArticleCount = `-- name: GetGroupArticleCount :one
SELECT COUNT(*)::int FROM article_group_members WHERE group_id = $1
`

func (q *Queries) GetGroupArticleCount(ctx context.Context, groupID int64) (int, error) {
	row := q.db.QueryRow(ctx, getGroupArticleCount, groupID)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const getGroupArticles = `-- name: GetGroupArticles :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.content, a.summary,
       a.author, a.published_date, a.fetched_date
FROM articles a
JOIN article_group_members agm ON a.id = agm.article_id
WHERE agm.group_id = $1
ORDER BY a.published_date DESC
`

type GetGroupArticlesRow struct {
	ID            int64
	FeedID        int64
	Guid          string
	Title         string
	Url           string
	Content       *string
	Summary       *string
	Author        *string
	PublishedDate *time.Time
	FetchedDate   time.Time
}

func (q *Queries) GetGroupArticles(ctx context.Context, groupID int64) ([]GetGroupArticlesRow, error) {
	rows, err := q.db.Query(ctx, getGroupArticles, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupArticlesRow{}
	for rows.Next() {
		var i GetGroupArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Content,
			&i.Summary,
			&i.Author,
			&i.PublishedDate,
			&i.FetchedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupEmbedding = `-- name: GetGroupEmbedding :one
SELECT embedding FROM article_groups WHERE id = $1
`

func (q *Queries) GetGroupEmbedding(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getGroupEmbedding, id)
	var embedding []byte
	err := row.Scan(&embedding)
	return embedding, err
}

const getGroupStats = `-- name: GetGroupStats :many
SELECT ag.id AS group_id,
       COALESCE(ag.display_name, ag.topic) AS display_name,
       SUM(CASE WHEN rs.read IS NULL OR rs.read = FALSE THEN 1 ELSE 0 END)::int AS unread_articles
FROM article_groups ag
JOIN article_group_members agm ON agm.group_id = ag.id
LEFT JOIN read_state rs ON rs.article_id = agm.article_id AND rs.user_id = $1
WHERE ag.user_id = $1 AND ag.muted = FALSE
GROUP BY ag.id
HAVING COUNT(agm.article_id) >= 2
   AND SUM(CASE WHEN rs.read IS NULL OR rs.read = FALSE THEN 1 ELSE 0 END) > 0
ORDER BY COALESCE(ag.display_name, ag.topic)
`

type GetGroupStatsRow struct {
	GroupID        int64
	DisplayName    string
	UnreadArticles int
}

func (q *Queries) GetGroupStats(ctx context.Context, userID int64) ([]GetGroupStatsRow, error) {
	rows, err := q.db.Query(ctx, getGroupStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupStatsRow{}
	for rows.Next() {
		var i GetGroupStatsRow
		if err := rows.Scan(&i.GroupID, &i.DisplayName, &i.UnreadArticles); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupSummary = `-- name: GetGroupSummary :one
SELECT group_id, headline, summary, article_count, max_interest_score, generated_at
FROM group_summaries WHERE group_id = $1
`

func (q *Queries) GetGroupSummary(ctx context.Context, groupID int64) (GroupSummary, error) {
	row := q.db.QueryRow(ctx, getGroupSummary, groupID)
	var i GroupSummary
	err := row.Scan(
		&i.GroupID,
		&i.Headline,
		&i.Summary,
		&i.ArticleCount,
		&i.MaxInterestScore,
		&i.GeneratedAt,
	)
	return i, err
}

const getGroupsWithEmbeddings = `-- name: GetGroupsWithEmbeddings :many
SELECT id, user_id, topic, display_name, muted, embedding, created_at, updated_at
FROM article_groups
WHERE user_id = $1 AND embedding IS NOT NULL AND embedding_model = $2
`

type GetGroupsWithEmbeddingsParams struct {
	UserID         int64
	EmbeddingModel string
}

type GetGroupsWithEmbeddingsRow struct {
	ID          int64
	UserID      int64
	Topic       string
	DisplayName *string
	Muted       bool
	Embedding   []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetGroupsWithEmbeddings(ctx context.Context, arg GetGroupsWithEmbeddingsParams) ([]GetGroupsWithEmbeddingsRow, error) {
	rows, err := q.db.Query(ctx, getGroupsWithEmbeddings, arg.UserID, arg.EmbeddingModel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupsWithEmbeddingsRow{}
	for rows.Next() {
		var i GetGroupsWithEmbeddingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Topic,
			&i.DisplayName,
			&i.Muted,
			&i.Embedding,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroups = `-- name: GetUserGroups :many
SELECT ag.id, ag.user_id, ag.topic, ag.display_name, ag.muted, ag.created_at, ag.updated_at
FROM article_groups ag
WHERE ag.user_id = $1
  AND (SELECT COUNT(*) FROM article_group_members WHERE group_id = ag.id) >= 2
ORDER BY ag.updated_at DESC
`

type GetUserGroupsRow struct {
	ID          int64
	UserID      int64
	Topic       string
	DisplayName *string
	Muted       bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetUserGroups(ctx context.Context, userID int64) ([]GetUserGroupsRow, error) {
	rows, err := q.db.Query(ctx, getUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserGroupsRow{}
	for rows.Next() {
		var i GetUserGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Topic,
			&i.DisplayName,
			&i.Muted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isGroupMuted = `-- name: IsGroupMuted :one
SELECT muted FROM article_groups WHERE id = $1
`

func (q *Queries) IsGroupMuted(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, isGroupMuted, id)
	var muted bool
	err := row.Scan(&muted)
	return muted, err
}

const setGroupMuted = `-- name: SetGroupMuted :exec
UPDATE article_groups SET muted = $1 WHERE id = $2
`

type SetGroupMutedParams struct {
	Muted bool
	ID    int64
}

func (q *Queries) SetGroupMuted(ctx context.Context, arg SetGroupMutedParams) error {
	_, err := q.db.Exec(ctx, setGroupMuted, arg.Muted, arg.ID)
	return err
}

const touchArticleGroup = `-- name: TouchArticleGroup :exec
UPDATE article_groups SET updated_at = NOW() WHERE id = $1
`

func (q *Queries) TouchArticleGroup(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchArticleGroup, id)
	return err
}

const updateGroupDisplayName = `-- name: UpdateGroupDisplayName :exec
UPDATE article_groups SET display_name = $1 WHERE id = $2
`

type UpdateGroupDisplayNameParams struct {
	DisplayName *string
	ID          int64
}

func (q *Queries) UpdateGroupDisplayName(ctx context.Context, arg UpdateGroupDisplayNameParams) error {
	_, err := q.db.Exec(ctx, updateGroupDisplayName, arg.DisplayName, arg.ID)
	return err
}

const updateGroupEmbedding = `-- name: UpdateGroupEmbedding :exec
UPDATE article_groups SET embedding = $1, embedding_model = $2 WHERE id = $3
`

type UpdateGroupEmbeddingParams struct {
	Embedding      []byte
	EmbeddingModel string
	ID             int64
}

func (q *Queries) UpdateGroupEmbedding(ctx context.Context, arg UpdateGroupEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateGroupEmbedding, arg.Embedding, arg.EmbeddingModel, arg.ID)
	return err
}

const updateGroupSummary = `-- name: UpdateGroupSummary :exec
INSERT INTO group_summaries (group_id, headline, summary, article_count, max_interest_score, generated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (group_id) DO UPDATE SET
  headline = excluded.headline,
  summary = excluded.summary,
  article_count = excluded.article_count,
  max_interest_score = excluded.max_interest_score,
  generated_at = NOW()
`

type UpdateGroupSummaryParams struct {
	GroupID          int64
	Headline         string
	Summary          string
	ArticleCount     int64
	MaxInterestScore *float64
}

func (q *Queries) UpdateGroupSummary(ctx context.Context, arg UpdateGroupSummaryParams) error {
	_, err := q.db.Exec(ctx, updateGroupSummary,
		arg.GroupID,
		arg.Headline,
		arg.Summary,
		arg.ArticleCount,
		arg.MaxInterestScore,
	)
	return err
}

const updateGroupTopic = `-- name: UpdateGroupTopic :exec
UPDATE article_groups SET topic = $1 WHERE id = $2
`

type UpdateGroupTopicParams struct {
	Topic string
	ID    int64
}

func (q *Queries) UpdateGroupTopic(ctx context.Context, arg UpdateGroupTopicParams) error {
	_, err := q.db.Exec(ctx, updateGroupTopic, arg.Topic, arg.ID)
	return err
}
