// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image.sql

package db

import (
	"context"
	"time"
)

const getArticleImage = `-- name: GetArticleImage :one
SELECT id, article_id, original_url, data, mime_type, width, height, fetched_at FROM article_images WHERE id = $1
`

func (q *Queries) GetArticleImage(ctx context.Context, id int64) (ArticleImage, error) {
	row := q.db.QueryRow(ctx, getArticleImage, id)
	var i ArticleImage
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.OriginalUrl,
		&i.Data,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.FetchedAt,
	)
	return i, err
}

const getArticleImageMap = `-- name: GetArticleImageMap :many
SELECT id, original_url FROM article_images WHERE article_id = $1
`

type GetArticleImageMapRow struct {
	ID          int64
	OriginalUrl string
}

func (q *Queries) GetArticleImageMap(ctx context.Context, articleID int64) ([]GetArticleImageMapRow, error) {
	rows, err := q.db.Query(ctx, getArticleImageMap, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetArticleImageMapRow{}
	for rows.Next() {
		var i GetArticleImageMapRow
		if err := rows.Scan(&i.ID, &i.OriginalUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArticlesNeedingImageCache = `-- name: GetArticlesNeedingImageCache :many
SELECT id, feed_id, guid, title, url, content, summary, author, published_date, fetched_date
FROM articles
WHERE images_cached = FALSE
ORDER BY fetched_date DESC
LIMIT $1
`

type GetArticlesNeedingImageCacheRow struct {
	ID            int64
	FeedID        int64
	Guid          string
	Title         string
	Url           string
	Content       *string
	Summary       *string
	Author        *string
	PublishedDate *time.Time
	FetchedDate   time.Time
}

func (q *Queries) GetArticlesNeedingImageCache(ctx context.Context, lim int32) ([]GetArticlesNeedingImageCacheRow, error) {
	rows, err := q.db.Query(ctx, getArticlesNeedingImageCache, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetArticlesNeedingImageCacheRow{}
	for rows.Next() {
		var i GetArticlesNeedingImageCacheRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Content,
			&i.Summary,
			&i.Author,
			&i.PublishedDate,
			&i.FetchedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markArticleImagesCached = `-- name: MarkArticleImagesCached :exec
UPDATE articles SET images_cached = TRUE WHERE id = $1
`

func (q *Queries) MarkArticleImagesCached(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markArticleImagesCached, id)
	return err
}

const storeArticleImage = `-- name: StoreArticleImage :one
INSERT INTO article_images (article_id, original_url, data, mime_type, width, height)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (article_id, original_url) DO UPDATE SET
  data = excluded.data,
  mime_type = excluded.mime_type,
  width = excluded.width,
  height = excluded.height,
  fetched_at = NOW()
RETURNING id
`

type StoreArticleImageParams struct {
	ArticleID   int64
	OriginalUrl string
	Data        []byte
	MimeType    string
	Width       int64
	Height      int64
}

func (q *Queries) StoreArticleImage(ctx context.Context, arg StoreArticleImageParams) (int64, error) {
	row := q.db.QueryRow(ctx, storeArticleImage,
		arg.ArticleID,
		arg.OriginalUrl,
		arg.Data,
		arg.MimeType,
		arg.Width,
		arg.Height,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
