// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metadata.sql

package db

import (
	"context"
)

const getArticleAuthors = `-- name: GetArticleAuthors :many
SELECT name, email FROM article_authors WHERE article_id = $1 ORDER BY name
`

type GetArticleAuthorsRow struct {
	Name  string
	Email *string
}

func (q *Queries) GetArticleAuthors(ctx context.Context, articleID int64) ([]GetArticleAuthorsRow, error) {
	rows, err := q.db.Query(ctx, getArticleAuthors, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetArticleAuthorsRow{}
	for rows.Next() {
		var i GetArticleAuthorsRow
		if err := rows.Scan(&i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArticleAuthorsBatch = `-- name: GetArticleAuthorsBatch :many
SELECT article_id, name FROM article_authors
WHERE article_id = ANY($1::bigint[])
ORDER BY article_id, name
`

type GetArticleAuthorsBatchRow struct {
	ArticleID int64
	Name      string
}

// Authors for a page of articles in one round trip. The per-article query above
// is an N+1 when a listing path needs metadata for every row it is about to
// score (#274).
func (q *Queries) GetArticleAuthorsBatch(ctx context.Context, articleIds []int64) ([]GetArticleAuthorsBatchRow, error) {
	rows, err := q.db.Query(ctx, getArticleAuthorsBatch, articleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetArticleAuthorsBatchRow{}
	for rows.Next() {
		var i GetArticleAuthorsBatchRow
		if err := rows.Scan(&i.ArticleID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArticleCategories = `-- name: GetArticleCategories :many
SELECT category FROM article_categories WHERE article_id = $1 ORDER BY category
`

func (q *Queries) GetArticleCategories(ctx context.Context, articleID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getArticleCategories, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArticleCategoriesBatch = `-- name: GetArticleCategoriesBatch :many
SELECT article_id, category FROM article_categories
WHERE article_id = ANY($1::bigint[])
ORDER BY article_id, category
`

func (q *Queries) GetArticleCategoriesBatch(ctx context.Context, articleIds []int64) ([]ArticleCategory, error) {
	rows, err := q.db.Query(ctx, getArticleCategoriesBatch, articleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArticleCategory{}
	for rows.Next() {
		var i ArticleCategory
		if err := rows.Scan(&i.ArticleID, &i.Category); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedAuthors = `-- name: GetFeedAuthors :many
SELECT DISTINCT aa.name FROM article_authors aa
JOIN articles a ON a.id = aa.article_id
WHERE a.feed_id = $1
ORDER BY aa.name
`

func (q *Queries) GetFeedAuthors(ctx context.Context, feedID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getFeedAuthors, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedCategories = `-- name: GetFeedCategories :many
SELECT DISTINCT ac.category FROM article_categories ac
JOIN articles a ON a.id = ac.article_id
WHERE a.feed_id = $1
ORDER BY ac.category
`

func (q *Queries) GetFeedCategories(ctx context.Context, feedID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getFeedCategories, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertArticleAuthor = `-- name: InsertArticleAuthor :exec
INSERT INTO article_authors (article_id, name, email)
VALUES ($1, $2, $3::text)
ON CONFLICT DO NOTHING
`

type InsertArticleAuthorParams struct {
	ArticleID int64
	Name      string
	Email     string
}

func (q *Queries) InsertArticleAuthor(ctx context.Context, arg InsertArticleAuthorParams) error {
	_, err := q.db.Exec(ctx, insertArticleAuthor, arg.ArticleID, arg.Name, arg.Email)
	return err
}

const insertArticleCategory = `-- name: InsertArticleCategory :exec
INSERT INTO article_categories (article_id, category)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertArticleCategoryParams struct {
	ArticleID int64
	Category  string
}

func (q *Queries) InsertArticleCategory(ctx context.Context, arg InsertArticleCategoryParams) error {
	_, err := q.db.Exec(ctx, insertArticleCategory, arg.ArticleID, arg.Category)
	return err
}
