// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/pgvector/pgvector-go"
)

type AiSummary struct {
	ID             int64
	UserID         int64
	NewsletterID   *int64
	Status         string
	Model          string
	Prompt         string
	Headline       string
	ContentHtml    string
	ArticleIdsJson string
	ArticleCount   int
	InputTokens    int
	OutputTokens   int
	Error          string
	CreatedAt      time.Time
	GeneratedAt    *time.Time
}

type Article struct {
	ID                 int64
	FeedID             int64
	Guid               string
	Title              string
	Url                string
	Content            *string
	Summary            *string
	Author             *string
	PublishedDate      *time.Time
	FetchedDate        time.Time
	LinkedUrl          string
	LinkedContent      string
	FullTextFetched    bool
	ImagesCached       bool
	SecurityScore      *float64
	SecurityReason     *string
	SecurityFlagged    bool
	SecurityScreenedAt *time.Time
	SecurityAttempts   int
	SearchVector       *string
	LinksExtracted     bool
}

type ArticleAuthor struct {
	ArticleID int64
	Name      string
	Email     *string
}

type ArticleCategory struct {
	ArticleID int64
	Category  string
}

type ArticleEmbedding struct {
	ArticleID       int64
	EmbeddingModel  string
	Status          int16
	Attempts        int
	ErrorMessage    *string
	LastAttemptedAt *time.Time
	CreatedAt       time.Time
	Embedding       *pgvector.Vector
}

type ArticleGroup struct {
	ID             int64
	UserID         int64
	Topic          string
	EmbeddingModel string
	DisplayName    *string
	Muted          bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Embedding      *pgvector.Vector
}

type ArticleGroupMember struct {
	GroupID   int64
	ArticleID int64
	AddedAt   time.Time
}

type ArticleImage struct {
	ID          int64
	ArticleID   int64
	OriginalUrl string
	Data        []byte
	MimeType    string
	Width       int64
	Height      int64
	FetchedAt   time.Time
}

type ArticleLink struct {
	ArticleID int64
	UrlNorm   string
}

type ArticleSummary struct {
	ArticleID   int64
	AiSummary   string
	SkipReason  *string
	GeneratedAt time.Time
}

type CycleStat struct {
	ID                 int64
	CompletedAt        time.Time
	DurationMs         int64
	FeedsTotal         int
	FeedsDownloaded    int
	FeedsNotModified   int
	FeedsErrored       int
	NewArticles        int
	Processed          int
	HighInterest       int
	AiBackendAvailable bool
}

type Feed struct {
	ID                int64
	Url               string
	Title             string
	Description       *string
	SiteUrl           string
	LastFetched       *time.Time
	LastError         *string
	Etag              *string
	LastModified      *string
	Enabled           bool
	CreatedAt         time.Time
	ConsecutiveErrors int64
	NextFetchAt       *time.Time
	Status            string
	FaviconFailedAt   *time.Time
	FaviconFailKind   string
}

type FeedFavicon struct {
	FeedID    int64
	Data      []byte
	MimeType  string
	FetchedAt time.Time
}

type FeedTag struct {
	UserID    int64
	FeedID    int64
	Tag       string
	CreatedAt time.Time
}

type FeverCredential struct {
	UserID int64
	ApiKey string
}

type FilterRule struct {
	ID        int64
	UserID    int64
	FeedID    *int64
	Axis      string
	Value     string
	Score     int64
	CreatedAt time.Time
}

type GroupSummary struct {
	GroupID          int64
	Headline         string
	Summary          string
	ArticleCount     int64
	MaxInterestScore *float64
	GeneratedAt      time.Time
}

type Newsletter struct {
	ID              int64
	UserID          int64
	Name            string
	Schedule        string
	ConfigJson      string
	PromptTemplate  string
	EmailRecipient  string
	Enabled         bool
	LastGeneratedAt *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type NewsletterIssue struct {
	ID             int64
	NewsletterID   int64
	Headline       string
	ContentHtml    string
	ContentText    string
	ArticleIdsJson string
	GeneratedAt    time.Time
	SentAt         *time.Time
}

type ReadState struct {
	UserID          int64
	ArticleID       int64
	Read            bool
	Starred         bool
	InterestScore   *float64
	SecurityScore   *float64
	ReadDate        *time.Time
	AiScored        bool
	AiRetries       int
	SecurityFlagged bool
	SecurityReason  *string
}

type Session struct {
	ID             string
	UserSub        string
	AccessToken    []byte
	RefreshToken   []byte
	Version        int64
	AccessExpiry   time.Time
	AbsoluteExpiry time.Time
	CreatedAt      time.Time
	LastUsedAt     time.Time
}

type User struct {
	ID        int64
	Name      string
	OidcSub   *string
	Email     *string
	CreatedAt time.Time
}

type UserFeed struct {
	UserID       int64
	FeedID       int64
	SubscribedAt time.Time
	UserTitle    *string
}

type UserPreference struct {
	ID     int64
	UserID int64
	Key    string
	Value  string
}

type UserPrompt struct {
	UserID         int64
	PromptType     string
	PromptTemplate string
	Temperature    *float64
	Model          *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
