// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: newsletter.sql

package db

import (
	"context"
	"time"
)

const createNewsletter = `-- name: CreateNewsletter :one
INSERT INTO newsletters (user_id, name, schedule, config_json, prompt_template, email_recipient, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateNewsletterParams struct {
	UserID         int64
	Name           string
	Schedule       string
	ConfigJson     string
	PromptTemplate string
	EmailRecipient string
	Enabled        bool
}

func (q *Queries) CreateNewsletter(ctx context.Context, arg CreateNewsletterParams) (int64, error) {
	row := q.db.QueryRow(ctx, createNewsletter,
		arg.UserID,
		arg.Name,
		arg.Schedule,
		arg.ConfigJson,
		arg.PromptTemplate,
		arg.EmailRecipient,
		arg.Enabled,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createNewsletterIssue = `-- name: CreateNewsletterIssue :one
INSERT INTO newsletter_issues (newsletter_id, headline, content_html, content_text, article_ids_json)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateNewsletterIssueParams struct {
	NewsletterID   int64
	Headline       string
	ContentHtml    string
	ContentText    string
	ArticleIdsJson string
}

func (q *Queries) CreateNewsletterIssue(ctx context.Context, arg CreateNewsletterIssueParams) (int64, error) {
	row := q.db.QueryRow(ctx, createNewsletterIssue,
		arg.NewsletterID,
		arg.Headline,
		arg.ContentHtml,
		arg.ContentText,
		arg.ArticleIdsJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteNewsletter = `-- name: DeleteNewsletter :exec
DELETE FROM newsletters WHERE id = $1
`

func (q *Queries) DeleteNewsletter(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteNewsletter, id)
	return err
}

const getDueNewsletters = `-- name: GetDueNewsletters :many
SELECT id, user_id, name, schedule, config_json, prompt_template, email_recipient, enabled, last_generated_at, created_at, updated_at FROM newsletters
WHERE enabled = TRUE AND schedule = $1
  AND (last_generated_at IS NULL OR last_generated_at < $2::timestamptz)
ORDER BY id
`

type GetDueNewslettersParams struct {
	Schedule string
	Cutoff   time.Time
}

func (q *Queries) GetDueNewsletters(ctx context.Context, arg GetDueNewslettersParams) ([]Newsletter, error) {
	rows, err := q.db.Query(ctx, getDueNewsletters, arg.Schedule, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Newsletter{}
	for rows.Next() {
		var i Newsletter
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Schedule,
			&i.ConfigJson,
			&i.PromptTemplate,
			&i.EmailRecipient,
			&i.Enabled,
			&i.LastGeneratedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestNewsletterIssue = `-- name: GetLatestNewsletterIssue :one
SELECT id, newsletter_id, headline, content_html, content_text, article_ids_json, generated_at, sent_at FROM newsletter_issues WHERE newsletter_id = $1
ORDER BY generated_at DESC LIMIT 1
`

func (q *Queries) GetLatestNewsletterIssue(ctx context.Context, newsletterID int64) (NewsletterIssue, error) {
	row := q.db.QueryRow(ctx, getLatestNewsletterIssue, newsletterID)
	var i NewsletterIssue
	err := row.Scan(
		&i.ID,
		&i.NewsletterID,
		&i.Headline,
		&i.ContentHtml,
		&i.ContentText,
		&i.ArticleIdsJson,
		&i.GeneratedAt,
		&i.SentAt,
	)
	return i, err
}

const getNewsletter = `-- name: GetNewsletter :one
SELECT id, user_id, name, schedule, config_json, prompt_template, email_recipient, enabled, last_generated_at, created_at, updated_at FROM newsletters WHERE id = $1
`

func (q *Queries) GetNewsletter(ctx context.Context, id int64) (Newsletter, error) {
	row := q.db.QueryRow(ctx, getNewsletter, id)
	var i Newsletter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Schedule,
		&i.ConfigJson,
		&i.PromptTemplate,
		&i.EmailRecipient,
		&i.Enabled,
		&i.LastGeneratedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNewsletterIssue = `-- name: GetNewsletterIssue :one
SELECT id, newsletter_id, headline, content_html, content_text, article_ids_json, generated_at, sent_at FROM newsletter_issues WHERE id = $1
`

func (q *Queries) GetNewsletterIssue(ctx context.Context, id int64) (NewsletterIssue, error) {
	row := q.db.QueryRow(ctx, getNewsletterIssue, id)
	var i NewsletterIssue
	err := row.Scan(
		&i.ID,
		&i.NewsletterID,
		&i.Headline,
		&i.ContentHtml,
		&i.ContentText,
		&i.ArticleIdsJson,
		&i.GeneratedAt,
		&i.SentAt,
	)
	return i, err
}

const getNewsletterIssues = `-- name: GetNewsletterIssues :many
SELECT id, newsletter_id, headline, content_text, generated_at, sent_at
FROM newsletter_issues WHERE newsletter_id = $1
ORDER BY generated_at DESC LIMIT $3 OFFSET $2
`

type GetNewsletterIssuesParams struct {
	NewsletterID int64
	Off          int32
	Lim          int32
}

type GetNewsletterIssuesRow struct {
	ID           int64
	NewsletterID int64
	Headline     string
	ContentText  string
	GeneratedAt  time.Time
	SentAt       *time.Time
}

func (q *Queries) GetNewsletterIssues(ctx context.Context, arg GetNewsletterIssuesParams) ([]GetNewsletterIssuesRow, error) {
	rows, err := q.db.Query(ctx, getNewsletterIssues, arg.NewsletterID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNewsletterIssuesRow{}
	for rows.Next() {
		var i GetNewsletterIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.NewsletterID,
			&i.Headline,
			&i.ContentText,
			&i.GeneratedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNewsletterStats = `-- name: GetNewsletterStats :many
SELECT n.id AS newsletter_id, n.name, COUNT(ni.id)::int AS issue_count
FROM newsletters n
LEFT JOIN newsletter_issues ni ON ni.newsletter_id = n.id
WHERE n.user_id = $1 AND n.enabled = TRUE
GROUP BY n.id, n.name
ORDER BY n.name
`

type GetNewsletterStatsRow struct {
	NewsletterID int64
	Name         string
	IssueCount   int
}

func (q *Queries) GetNewsletterStats(ctx context.Context, userID int64) ([]GetNewsletterStatsRow, error) {
	rows, err := q.db.Query(ctx, getNewsletterStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNewsletterStatsRow{}
	for rows.Next() {
		var i GetNewsletterStatsRow
		if err := rows.Scan(&i.NewsletterID, &i.Name, &i.IssueCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserNewsletters = `-- name: GetUserNewsletters :many
SELECT id, user_id, name, schedule, config_json, prompt_template, email_recipient, enabled, last_generated_at, created_at, updated_at FROM newsletters WHERE user_id = $1 ORDER BY name
`

func (q *Queries) GetUserNewsletters(ctx context.Context, userID int64) ([]Newsletter, error) {
	rows, err := q.db.Query(ctx, getUserNewsletters, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Newsletter{}
	for rows.Next() {
		var i Newsletter
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Schedule,
			&i.ConfigJson,
			&i.PromptTemplate,
			&i.EmailRecipient,
			&i.Enabled,
			&i.LastGeneratedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNewsletterIssueSent = `-- name: MarkNewsletterIssueSent :exec
UPDATE newsletter_issues SET sent_at = NOW() WHERE id = $1
`

func (q *Queries) MarkNewsletterIssueSent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markNewsletterIssueSent, id)
	return err
}

const updateNewsletter = `-- name: UpdateNewsletter :exec
UPDATE newsletters
SET name = $1, schedule = $2, config_json = $3,
    prompt_template = $4, email_recipient = $5,
    enabled = $6, updated_at = NOW()
WHERE id = $7
`

type UpdateNewsletterParams struct {
	Name           string
	Schedule       string
	ConfigJson     string
	PromptTemplate string
	EmailRecipient string
	Enabled        bool
	ID             int64
}

func (q *Queries) UpdateNewsletter(ctx context.Context, arg UpdateNewsletterParams) error {
	_, err := q.db.Exec(ctx, updateNewsletter,
		arg.Name,
		arg.Schedule,
		arg.ConfigJson,
		arg.PromptTemplate,
		arg.EmailRecipient,
		arg.Enabled,
		arg.ID,
	)
	return err
}

const updateNewsletterLastGenerated = `-- name: UpdateNewsletterLastGenerated :exec
UPDATE newsletters SET last_generated_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateNewsletterLastGenerated(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateNewsletterLastGenerated, id)
	return err
}
