// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prompt.sql

package db

import (
	"context"
	"time"
)

const deleteUserPreference = `-- name: DeleteUserPreference :exec
DELETE FROM user_preferences WHERE user_id = $1 AND key = $2
`

type DeleteUserPreferenceParams struct {
	UserID int64
	Key    string
}

func (q *Queries) DeleteUserPreference(ctx context.Context, arg DeleteUserPreferenceParams) error {
	_, err := q.db.Exec(ctx, deleteUserPreference, arg.UserID, arg.Key)
	return err
}

const deleteUserPrompt = `-- name: DeleteUserPrompt :exec
DELETE FROM user_prompts WHERE user_id = $1 AND prompt_type = $2
`

type DeleteUserPromptParams struct {
	UserID     int64
	PromptType string
}

func (q *Queries) DeleteUserPrompt(ctx context.Context, arg DeleteUserPromptParams) error {
	_, err := q.db.Exec(ctx, deleteUserPrompt, arg.UserID, arg.PromptType)
	return err
}

const getAllUserPreferences = `-- name: GetAllUserPreferences :many
SELECT key, value FROM user_preferences WHERE user_id = $1
`

type GetAllUserPreferencesRow struct {
	Key   string
	Value string
}

func (q *Queries) GetAllUserPreferences(ctx context.Context, userID int64) ([]GetAllUserPreferencesRow, error) {
	rows, err := q.db.Query(ctx, getAllUserPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllUserPreferencesRow{}
	for rows.Next() {
		var i GetAllUserPreferencesRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPreference = `-- name: GetUserPreference :one
SELECT value FROM user_preferences WHERE user_id = $1 AND key = $2
`

type GetUserPreferenceParams struct {
	UserID int64
	Key    string
}

func (q *Queries) GetUserPreference(ctx context.Context, arg GetUserPreferenceParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserPreference, arg.UserID, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getUserPrompt = `-- name: GetUserPrompt :one
SELECT prompt_template FROM user_prompts
WHERE user_id = $1 AND prompt_type = $2
`

type GetUserPromptParams struct {
	UserID     int64
	PromptType string
}

func (q *Queries) GetUserPrompt(ctx context.Context, arg GetUserPromptParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserPrompt, arg.UserID, arg.PromptType)
	var prompt_template string
	err := row.Scan(&prompt_template)
	return prompt_template, err
}

const getUserPromptModel = `-- name: GetUserPromptModel :one
SELECT model FROM user_prompts
WHERE user_id = $1 AND prompt_type = $2
`

type GetUserPromptModelParams struct {
	UserID     int64
	PromptType string
}

func (q *Queries) GetUserPromptModel(ctx context.Context, arg GetUserPromptModelParams) (*string, error) {
	row := q.db.QueryRow(ctx, getUserPromptModel, arg.UserID, arg.PromptType)
	var model *string
	err := row.Scan(&model)
	return model, err
}

const getUserPromptTemperature = `-- name: GetUserPromptTemperature :one
SELECT temperature FROM user_prompts
WHERE user_id = $1 AND prompt_type = $2
`

type GetUserPromptTemperatureParams struct {
	UserID     int64
	PromptType string
}

func (q *Queries) GetUserPromptTemperature(ctx context.Context, arg GetUserPromptTemperatureParams) (*float64, error) {
	row := q.db.QueryRow(ctx, getUserPromptTemperature, arg.UserID, arg.PromptType)
	var temperature *float64
	err := row.Scan(&temperature)
	return temperature, err
}

const listUserPrompts = `-- name: ListUserPrompts :many
SELECT prompt_type, prompt_template, temperature, model, created_at, updated_at
FROM user_prompts
WHERE user_id = $1
ORDER BY prompt_type
`

type ListUserPromptsRow struct {
	PromptType     string
	PromptTemplate string
	Temperature    *float64
	Model          *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) ListUserPrompts(ctx context.Context, userID int64) ([]ListUserPromptsRow, error) {
	rows, err := q.db.Query(ctx, listUserPrompts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserPromptsRow{}
	for rows.Next() {
		var i ListUserPromptsRow
		if err := rows.Scan(
			&i.PromptType,
			&i.PromptTemplate,
			&i.Temperature,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserPreference = `-- name: SetUserPreference :exec
INSERT INTO user_preferences (user_id, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, key) DO UPDATE SET value = excluded.value
`

type SetUserPreferenceParams struct {
	UserID int64
	Key    string
	Value  string
}

func (q *Queries) SetUserPreference(ctx context.Context, arg SetUserPreferenceParams) error {
	_, err := q.db.Exec(ctx, setUserPreference, arg.UserID, arg.Key, arg.Value)
	return err
}

const setUserPrompt = `-- name: SetUserPrompt :exec
INSERT INTO user_prompts (user_id, prompt_type, prompt_template, temperature, model, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (user_id, prompt_type) DO UPDATE SET
  prompt_template = excluded.prompt_template,
  temperature = excluded.temperature,
  model = COALESCE(excluded.model, user_prompts.model),
  updated_at = NOW()
`

type SetUserPromptParams struct {
	UserID         int64
	PromptType     string
	PromptTemplate string
	Temperature    *float64
	Model          *string
}

func (q *Queries) SetUserPrompt(ctx context.Context, arg SetUserPromptParams) error {
	_, err := q.db.Exec(ctx, setUserPrompt,
		arg.UserID,
		arg.PromptType,
		arg.PromptTemplate,
		arg.Temperature,
		arg.Model,
	)
	return err
}
