// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: read_state.sql

package db

import (
	"context"
)

const getScoreStats = `-- name: GetScoreStats :many
SELECT
  f.id AS feed_id,
  COALESCE(uf.user_title, f.title) AS feed_title,
  COUNT(*) FILTER (WHERE a.security_screened_at IS NOT NULL)::int AS total_scored,
  COUNT(*) FILTER (WHERE a.security_threat <= 3.0)::int AS sec_pass,
  COUNT(*) FILTER (WHERE a.security_threat > 3.0 AND a.security_threat <= 6.0)::int AS sec_borderline,
  COUNT(*) FILTER (WHERE a.security_threat IS NOT NULL AND a.security_threat > 6.0)::int AS sec_fail,
  -- Screened but skipped (no content / too short): security_screened_at set,
  -- threat left NULL. Counted separately so it isn't mistaken for a pass and so
  -- total_scored = sec_pass + sec_borderline + sec_fail + sec_skipped (#123).
  COUNT(*) FILTER (WHERE a.security_screened_at IS NOT NULL AND a.security_threat IS NULL)::int AS sec_skipped,
  COUNT(*) FILTER (WHERE a.security_threat <= 3.0 AND rs.interest_score >= 8.0)::int AS int_high,
  COUNT(*) FILTER (WHERE a.security_threat <= 3.0 AND rs.interest_score >= 5.0 AND rs.interest_score < 8.0)::int AS int_medium,
  COUNT(*) FILTER (WHERE a.security_threat <= 3.0 AND rs.interest_score IS NOT NULL AND rs.interest_score < 5.0)::int AS int_low
FROM feeds f
JOIN user_feeds uf ON uf.feed_id = f.id AND uf.user_id = $1
JOIN articles a ON a.feed_id = f.id
LEFT JOIN read_state rs ON rs.article_id = a.id AND rs.user_id = $1
GROUP BY f.id, uf.user_title, f.title
ORDER BY COALESCE(uf.user_title, f.title)
`

type GetScoreStatsRow struct {
	FeedID        int64
	FeedTitle     string
	TotalScored   int
	SecPass       int
	SecBorderline int
	SecFail       int
	SecSkipped    int
	IntHigh       int
	IntMedium     int
	IntLow        int
}

func (q *Queries) GetScoreStats(ctx context.Context, userID int64) ([]GetScoreStatsRow, error) {
	rows, err := q.db.Query(ctx, getScoreStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetScoreStatsRow{}
	for rows.Next() {
		var i GetScoreStatsRow
		if err := rows.Scan(
			&i.FeedID,
			&i.FeedTitle,
			&i.TotalScored,
			&i.SecPass,
			&i.SecBorderline,
			&i.SecFail,
			&i.SecSkipped,
			&i.IntHigh,
			&i.IntMedium,
			&i.IntLow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementAIRetries = `-- name: IncrementAIRetries :exec
INSERT INTO read_state (user_id, article_id, ai_retries)
VALUES ($1, $2, 1)
ON CONFLICT (user_id, article_id) DO UPDATE SET
  ai_retries = read_state.ai_retries + 1
`

type IncrementAIRetriesParams struct {
	UserID    int64
	ArticleID int64
}

func (q *Queries) IncrementAIRetries(ctx context.Context, arg IncrementAIRetriesParams) error {
	_, err := q.db.Exec(ctx, incrementAIRetries, arg.UserID, arg.ArticleID)
	return err
}

const resetArticleScores = `-- name: ResetArticleScores :execrows
UPDATE articles
SET security_threat = NULL, security_category = NULL, security_verified = NULL,
    security_flagged = FALSE, security_screened_at = NULL, security_attempts = 0
WHERE feed_id IN (SELECT feed_id FROM user_feeds WHERE user_id = $1)
`

func (q *Queries) ResetArticleScores(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, resetArticleScores, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetArticleScoresBelow = `-- name: ResetArticleScoresBelow :execrows
UPDATE articles
SET security_threat = NULL, security_category = NULL, security_verified = NULL,
    security_flagged = FALSE, security_screened_at = NULL, security_attempts = 0
WHERE feed_id IN (SELECT feed_id FROM user_feeds WHERE user_id = $1)
  AND security_threat IS NOT NULL AND security_threat > $2::double precision
`

type ResetArticleScoresBelowParams struct {
	UserID      int64
	AboveThreat float64
}

// Re-screen articles that previously FAILED: on the threat scale that is a HIGH
// score (above the ceiling), where the old safety scale made it a LOW one.
func (q *Queries) ResetArticleScoresBelow(ctx context.Context, arg ResetArticleScoresBelowParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetArticleScoresBelow, arg.UserID, arg.AboveThreat)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetReadStateScores = `-- name: ResetReadStateScores :exec
UPDATE read_state SET ai_scored = FALSE, ai_retries = 0, interest_score = NULL
WHERE user_id = $1
`

func (q *Queries) ResetReadStateScores(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, resetReadStateScores, userID)
	return err
}

const updateStarred = `-- name: UpdateStarred :exec
INSERT INTO read_state (user_id, article_id, starred)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, article_id) DO UPDATE SET starred = excluded.starred
`

type UpdateStarredParams struct {
	UserID    int64
	ArticleID int64
	Starred   bool
}

func (q *Queries) UpdateStarred(ctx context.Context, arg UpdateStarredParams) error {
	_, err := q.db.Exec(ctx, updateStarred, arg.UserID, arg.ArticleID, arg.Starred)
	return err
}

const upsertReadStateRead = `-- name: UpsertReadStateRead :exec
INSERT INTO read_state (user_id, article_id, read, read_date)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_id, article_id) DO UPDATE SET
  read = excluded.read,
  read_date = NOW()
`

type UpsertReadStateReadParams struct {
	UserID    int64
	ArticleID int64
	Read      bool
}

func (q *Queries) UpsertReadStateRead(ctx context.Context, arg UpsertReadStateReadParams) error {
	_, err := q.db.Exec(ctx, upsertReadStateRead, arg.UserID, arg.ArticleID, arg.Read)
	return err
}

const upsertReadStateScores = `-- name: UpsertReadStateScores :exec
INSERT INTO read_state
  (user_id, article_id, read, interest_score, security_threat, security_category, security_verified, security_flagged, ai_scored)
VALUES
  ($1, $2, FALSE, $3, $4, $5, $6, COALESCE($7, FALSE), TRUE)
ON CONFLICT (user_id, article_id) DO UPDATE SET
  interest_score = excluded.interest_score,
  security_threat = excluded.security_threat,
  security_category = excluded.security_category,
  security_verified = excluded.security_verified,
  security_flagged = COALESCE(excluded.security_flagged, read_state.security_flagged),
  ai_scored = TRUE
`

type UpsertReadStateScoresParams struct {
	UserID           int64
	ArticleID        int64
	InterestScore    *float64
	SecurityThreat   *float64
	SecurityCategory *string
	SecurityVerified *bool
	SecurityFlagged  interface{}
}

// AI pipeline: record scores, mark ai_scored, leave the user's read flag alone.
func (q *Queries) UpsertReadStateScores(ctx context.Context, arg UpsertReadStateScoresParams) error {
	_, err := q.db.Exec(ctx, upsertReadStateScores,
		arg.UserID,
		arg.ArticleID,
		arg.InterestScore,
		arg.SecurityThreat,
		arg.SecurityCategory,
		arg.SecurityVerified,
		arg.SecurityFlagged,
	)
	return err
}

const userSubscribedToArticleFeed = `-- name: UserSubscribedToArticleFeed :one
SELECT EXISTS(
  SELECT 1 FROM articles a
  JOIN user_feeds uf ON uf.feed_id = a.feed_id AND uf.user_id = $1
  WHERE a.id = $2
)
`

type UserSubscribedToArticleFeedParams struct {
	UserID    int64
	ArticleID int64
}

func (q *Queries) UserSubscribedToArticleFeed(ctx context.Context, arg UserSubscribedToArticleFeedParams) (bool, error) {
	row := q.db.QueryRow(ctx, userSubscribedToArticleFeed, arg.UserID, arg.ArticleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
