// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package db

import (
	"context"
	"time"
)

const searchArticlesFTS = `-- name: SearchArticlesFTS :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.content, a.summary,
       a.author, a.published_date, a.fetched_date,
       COALESCE(a.security_flagged, FALSE) AS security_flagged,
       COALESCE(rs.read, FALSE) AS is_read, COALESCE(rs.starred, FALSE) AS is_starred
FROM articles a
JOIN user_feeds uf ON a.feed_id = uf.feed_id
LEFT JOIN read_state rs ON rs.article_id = a.id AND rs.user_id = $1
WHERE uf.user_id = $1 AND a.search_vector @@ websearch_to_tsquery('english', $2)
ORDER BY ts_rank_cd(a.search_vector, websearch_to_tsquery('english', $2)) DESC
LIMIT $4 OFFSET $3
`

type SearchArticlesFTSParams struct {
	UserID int64
	Query  string
	Off    int32
	Lim    int32
}

type SearchArticlesFTSRow struct {
	ID              int64
	FeedID          int64
	Guid            string
	Title           string
	Url             string
	Content         *string
	Summary         *string
	Author          *string
	PublishedDate   *time.Time
	FetchedDate     time.Time
	SecurityFlagged bool
	IsRead          bool
	IsStarred       bool
}

func (q *Queries) SearchArticlesFTS(ctx context.Context, arg SearchArticlesFTSParams) ([]SearchArticlesFTSRow, error) {
	rows, err := q.db.Query(ctx, searchArticlesFTS,
		arg.UserID,
		arg.Query,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchArticlesFTSRow{}
	for rows.Next() {
		var i SearchArticlesFTSRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Content,
			&i.Summary,
			&i.Author,
			&i.PublishedDate,
			&i.FetchedDate,
			&i.SecurityFlagged,
			&i.IsRead,
			&i.IsStarred,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
