// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions
  (id, user_sub, access_token, refresh_token, access_expiry, absolute_expiry)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSessionParams struct {
	ID             string
	UserSub        string
	AccessToken    []byte
	RefreshToken   []byte
	AccessExpiry   time.Time
	AbsoluteExpiry time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserSub,
		arg.AccessToken,
		arg.RefreshToken,
		arg.AccessExpiry,
		arg.AbsoluteExpiry,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE absolute_expiry <= $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_sub, access_token, refresh_token, version,
       access_expiry, absolute_expiry, created_at
FROM sessions
WHERE id = $1
`

type GetSessionRow struct {
	ID             string
	UserSub        string
	AccessToken    []byte
	RefreshToken   []byte
	Version        int64
	AccessExpiry   time.Time
	AbsoluteExpiry time.Time
	CreatedAt      time.Time
}

func (q *Queries) GetSession(ctx context.Context, id string) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserSub,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Version,
		&i.AccessExpiry,
		&i.AbsoluteExpiry,
		&i.CreatedAt,
	)
	return i, err
}

const rotateSessionTokens = `-- name: RotateSessionTokens :execrows
UPDATE sessions
SET access_token = $1,
    refresh_token = $2,
    access_expiry = $3,
    version = version + 1,
    last_used_at = $4
WHERE id = $5 AND version = $6
`

type RotateSessionTokensParams struct {
	AccessToken   []byte
	RefreshToken  []byte
	AccessExpiry  time.Time
	LastUsedAt    time.Time
	ID            string
	ExpectVersion int64
}

// Compare-and-swap on the version counter: write new tokens and bump the
// version only if the stored version still matches the one the caller read.
func (q *Queries) RotateSessionTokens(ctx context.Context, arg RotateSessionTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateSessionTokens,
		arg.AccessToken,
		arg.RefreshToken,
		arg.AccessExpiry,
		arg.LastUsedAt,
		arg.ID,
		arg.ExpectVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
