// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package db

import (
	"context"
	"time"
)

const getFeedStats = `-- name: GetFeedStats :many
SELECT
  f.id AS feed_id,
  COALESCE(uf.user_title, f.title) AS feed_title,
  COUNT(a.id)::int AS total_articles,
  COALESCE(SUM(CASE WHEN (rs.read IS NULL OR rs.read = FALSE)
           AND NOT EXISTS (
             SELECT 1 FROM article_group_members agm
             JOIN article_groups ag ON agm.group_id = ag.id
             WHERE agm.article_id = a.id AND ag.user_id = uf.user_id
           ) THEN 1 ELSE 0 END), 0)::int AS unread_articles,
  (COUNT(a.id) - COUNT(asumm.article_id))::int AS unsummarized_articles,
  MAX(a.published_date) AS last_post_date
FROM feeds f
JOIN user_feeds uf ON uf.feed_id = f.id AND uf.user_id = $1
JOIN articles a ON a.feed_id = f.id
LEFT JOIN read_state rs ON rs.article_id = a.id AND rs.user_id = $1
LEFT JOIN article_summaries asumm ON asumm.article_id = a.id
GROUP BY f.id, uf.user_title
ORDER BY COALESCE(uf.user_title, f.title)
`

type GetFeedStatsRow struct {
	FeedID               int64
	FeedTitle            string
	TotalArticles        int
	UnreadArticles       int
	UnsummarizedArticles int
	LastPostDate         interface{}
}

func (q *Queries) GetFeedStats(ctx context.Context, userID int64) ([]GetFeedStatsRow, error) {
	rows, err := q.db.Query(ctx, getFeedStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFeedStatsRow{}
	for rows.Next() {
		var i GetFeedStatsRow
		if err := rows.Scan(
			&i.FeedID,
			&i.FeedTitle,
			&i.TotalArticles,
			&i.UnreadArticles,
			&i.UnsummarizedArticles,
			&i.LastPostDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProcessingFeedCounts = `-- name: GetProcessingFeedCounts :one
SELECT
  (SELECT COUNT(*) FROM user_feeds WHERE user_feeds.user_id = $1)::int AS feeds_total,
  (SELECT COUNT(*) FROM feeds f
   JOIN user_feeds uf ON uf.feed_id = f.id
   WHERE uf.user_id = $1 AND f.consecutive_errors > 0)::int AS feeds_erroring
`

type GetProcessingFeedCountsRow struct {
	FeedsTotal    int
	FeedsErroring int
}

func (q *Queries) GetProcessingFeedCounts(ctx context.Context, userID int64) (GetProcessingFeedCountsRow, error) {
	row := q.db.QueryRow(ctx, getProcessingFeedCounts, userID)
	var i GetProcessingFeedCountsRow
	err := row.Scan(&i.FeedsTotal, &i.FeedsErroring)
	return i, err
}

const getProcessingFunnel = `-- name: GetProcessingFunnel :one
SELECT
  COUNT(*)::int AS total_articles,
  COALESCE(SUM(CASE WHEN a.security_screened_at IS NOT NULL THEN 1 ELSE 0 END), 0)::int AS scored,
  COALESCE(SUM(CASE WHEN a.security_screened_at IS NULL AND a.security_attempts < 3 THEN 1 ELSE 0 END), 0)::int AS pending,
  COALESCE(SUM(CASE WHEN a.security_screened_at IS NULL AND a.security_attempts >= 3 THEN 1 ELSE 0 END), 0)::int AS stuck,
  COALESCE(SUM(CASE WHEN a.security_score >= 7 THEN 1 ELSE 0 END), 0)::int AS security_passed,
  COALESCE(SUM(CASE WHEN a.security_score IS NOT NULL AND a.security_score < 7 THEN 1 ELSE 0 END), 0)::int AS security_rejected,
  COALESCE(SUM(CASE WHEN a.security_screened_at IS NOT NULL AND a.security_score IS NULL THEN 1 ELSE 0 END), 0)::int AS security_skipped,
  COALESCE(SUM(CASE WHEN rs.interest_score IS NOT NULL THEN 1 ELSE 0 END), 0)::int AS curated
FROM articles a
JOIN user_feeds uf ON uf.feed_id = a.feed_id AND uf.user_id = $1
LEFT JOIN read_state rs ON rs.article_id = a.id AND rs.user_id = $1
`

type GetProcessingFunnelRow struct {
	TotalArticles    int
	Scored           int
	Pending          int
	Stuck            int
	SecurityPassed   int
	SecurityRejected int
	SecuritySkipped  int
	Curated          int
}

func (q *Queries) GetProcessingFunnel(ctx context.Context, userID int64) (GetProcessingFunnelRow, error) {
	row := q.db.QueryRow(ctx, getProcessingFunnel, userID)
	var i GetProcessingFunnelRow
	err := row.Scan(
		&i.TotalArticles,
		&i.Scored,
		&i.Pending,
		&i.Stuck,
		&i.SecurityPassed,
		&i.SecurityRejected,
		&i.SecuritySkipped,
		&i.Curated,
	)
	return i, err
}

const getProcessingSummaryCounts = `-- name: GetProcessingSummaryCounts :one
SELECT
  (SELECT COUNT(*) FROM article_summaries WHERE ai_summary <> '')::int AS summarized,
  (SELECT COUNT(*) FROM article_summaries WHERE COALESCE(skip_reason, '') <> '')::int AS summarize_skipped
`

type GetProcessingSummaryCountsRow struct {
	Summarized       int
	SummarizeSkipped int
}

// Summaries are per-article and shared by all subscribers (#162), so these two
// funnel numbers are global, like the security columns above.
func (q *Queries) GetProcessingSummaryCounts(ctx context.Context) (GetProcessingSummaryCountsRow, error) {
	row := q.db.QueryRow(ctx, getProcessingSummaryCounts)
	var i GetProcessingSummaryCountsRow
	err := row.Scan(&i.Summarized, &i.SummarizeSkipped)
	return i, err
}

const getRecentCycleStats = `-- name: GetRecentCycleStats :many
SELECT id, completed_at, duration_ms, feeds_total, feeds_downloaded, feeds_not_modified, feeds_errored, new_articles, processed, high_interest, ai_backend_available FROM cycle_stats ORDER BY completed_at DESC LIMIT $1
`

func (q *Queries) GetRecentCycleStats(ctx context.Context, lim int32) ([]CycleStat, error) {
	rows, err := q.db.Query(ctx, getRecentCycleStats, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CycleStat{}
	for rows.Next() {
		var i CycleStat
		if err := rows.Scan(
			&i.ID,
			&i.CompletedAt,
			&i.DurationMs,
			&i.FeedsTotal,
			&i.FeedsDownloaded,
			&i.FeedsNotModified,
			&i.FeedsErrored,
			&i.NewArticles,
			&i.Processed,
			&i.HighInterest,
			&i.AiBackendAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneCycleStats = `-- name: PruneCycleStats :exec
DELETE FROM cycle_stats WHERE id NOT IN (
  SELECT id FROM cycle_stats ORDER BY completed_at DESC LIMIT 500)
`

// Keep the most recent 500 cycles (~10 days at a 30m cadence).
func (q *Queries) PruneCycleStats(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneCycleStats)
	return err
}

const recordCycleStats = `-- name: RecordCycleStats :exec
INSERT INTO cycle_stats
  (completed_at, duration_ms, feeds_total, feeds_downloaded, feeds_not_modified,
   feeds_errored, new_articles, processed, high_interest, ai_backend_available)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9, $10)
`

type RecordCycleStatsParams struct {
	CompletedAt        time.Time
	DurationMs         int64
	FeedsTotal         int
	FeedsDownloaded    int
	FeedsNotModified   int
	FeedsErrored       int
	NewArticles        int
	Processed          int
	HighInterest       int
	AiBackendAvailable bool
}

func (q *Queries) RecordCycleStats(ctx context.Context, arg RecordCycleStatsParams) error {
	_, err := q.db.Exec(ctx, recordCycleStats,
		arg.CompletedAt,
		arg.DurationMs,
		arg.FeedsTotal,
		arg.FeedsDownloaded,
		arg.FeedsNotModified,
		arg.FeedsErrored,
		arg.NewArticles,
		arg.Processed,
		arg.HighInterest,
		arg.AiBackendAvailable,
	)
	return err
}
