// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscription.sql

package db

import (
	"context"
	"time"
)

const countFeedSubscribers = `-- name: CountFeedSubscribers :one
SELECT COUNT(*) FROM user_feeds WHERE feed_id = $1
`

func (q *Queries) CountFeedSubscribers(ctx context.Context, feedID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFeedSubscribers, feedID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFeedArticlesBatch = `-- name: DeleteFeedArticlesBatch :execrows
DELETE FROM articles
WHERE id IN (SELECT a.id FROM articles a WHERE a.feed_id = $1 LIMIT $2)
`

type DeleteFeedArticlesBatchParams struct {
	FeedID int64
	Lim    int32
}

func (q *Queries) DeleteFeedArticlesBatch(ctx context.Context, arg DeleteFeedArticlesBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFeedArticlesBatch, arg.FeedID, arg.Lim)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOrphanedFeed = `-- name: DeleteOrphanedFeed :execrows
DELETE FROM feeds
WHERE id = $1 AND NOT EXISTS (SELECT 1 FROM user_feeds WHERE user_feeds.feed_id = $1)
`

func (q *Queries) DeleteOrphanedFeed(ctx context.Context, feedID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrphanedFeed, feedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllActiveSubscribedFeeds = `-- name: GetAllActiveSubscribedFeeds :many
SELECT DISTINCT f.id, f.url, f.title, f.description, f.site_url, f.last_fetched, f.last_error, f.etag, f.last_modified, f.enabled, f.created_at, f.consecutive_errors, f.next_fetch_at, f.status FROM feeds f
JOIN user_feeds uf ON f.id = uf.feed_id
WHERE f.enabled = TRUE
ORDER BY f.title
`

func (q *Queries) GetAllActiveSubscribedFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.Query(ctx, getAllActiveSubscribedFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.SiteUrl,
			&i.LastFetched,
			&i.LastError,
			&i.Etag,
			&i.LastModified,
			&i.Enabled,
			&i.CreatedAt,
			&i.ConsecutiveErrors,
			&i.NextFetchAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSubscribedFeeds = `-- name: GetAllSubscribedFeeds :many
SELECT DISTINCT f.id, f.url, f.title, f.description, f.site_url, f.last_fetched, f.last_error, f.etag, f.last_modified, f.enabled, f.created_at, f.consecutive_errors, f.next_fetch_at, f.status FROM feeds f
JOIN user_feeds uf ON f.id = uf.feed_id
WHERE f.enabled = TRUE AND f.status = 'active'
  AND (f.next_fetch_at IS NULL OR f.next_fetch_at <= NOW())
ORDER BY f.title
`

func (q *Queries) GetAllSubscribedFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.Query(ctx, getAllSubscribedFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.SiteUrl,
			&i.LastFetched,
			&i.LastError,
			&i.Etag,
			&i.LastModified,
			&i.Enabled,
			&i.CreatedAt,
			&i.ConsecutiveErrors,
			&i.NextFetchAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSubscribingUsers = `-- name: GetAllSubscribingUsers :many
SELECT DISTINCT user_id FROM user_feeds ORDER BY user_id
`

func (q *Queries) GetAllSubscribingUsers(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, getAllSubscribingUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedSubscribers = `-- name: GetFeedSubscribers :many
SELECT user_id FROM user_feeds WHERE feed_id = $1
`

func (q *Queries) GetFeedSubscribers(ctx context.Context, feedID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getFeedSubscribers, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFeeds = `-- name: GetUserFeeds :many
SELECT f.id, f.url, COALESCE(uf.user_title, f.title) AS title, f.description,
       f.site_url, f.last_fetched, f.last_error, f.etag, f.last_modified,
       f.enabled, f.created_at, f.consecutive_errors, f.next_fetch_at, f.status
FROM feeds f
JOIN user_feeds uf ON f.id = uf.feed_id
WHERE uf.user_id = $1 AND f.enabled = TRUE
ORDER BY COALESCE(uf.user_title, f.title)
`

type GetUserFeedsRow struct {
	ID                int64
	Url               string
	Title             string
	Description       *string
	SiteUrl           string
	LastFetched       *time.Time
	LastError         *string
	Etag              *string
	LastModified      *string
	Enabled           bool
	CreatedAt         time.Time
	ConsecutiveErrors int64
	NextFetchAt       *time.Time
	Status            string
}

func (q *Queries) GetUserFeeds(ctx context.Context, userID int64) ([]GetUserFeedsRow, error) {
	rows, err := q.db.Query(ctx, getUserFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserFeedsRow{}
	for rows.Next() {
		var i GetUserFeedsRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.SiteUrl,
			&i.LastFetched,
			&i.LastError,
			&i.Etag,
			&i.LastModified,
			&i.Enabled,
			&i.CreatedAt,
			&i.ConsecutiveErrors,
			&i.NextFetchAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscribeUserToFeed = `-- name: SubscribeUserToFeed :exec
INSERT INTO user_feeds (user_id, feed_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type SubscribeUserToFeedParams struct {
	UserID int64
	FeedID int64
}

func (q *Queries) SubscribeUserToFeed(ctx context.Context, arg SubscribeUserToFeedParams) error {
	_, err := q.db.Exec(ctx, subscribeUserToFeed, arg.UserID, arg.FeedID)
	return err
}

const unsubscribeUserFromFeed = `-- name: UnsubscribeUserFromFeed :exec
DELETE FROM user_feeds WHERE user_id = $1 AND feed_id = $2
`

type UnsubscribeUserFromFeedParams struct {
	UserID int64
	FeedID int64
}

func (q *Queries) UnsubscribeUserFromFeed(ctx context.Context, arg UnsubscribeUserFromFeedParams) error {
	_, err := q.db.Exec(ctx, unsubscribeUserFromFeed, arg.UserID, arg.FeedID)
	return err
}
