// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name) VALUES ($1) RETURNING id
`

func (q *Queries) CreateUser(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, createUser, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUserWithOIDC = `-- name: CreateUserWithOIDC :one
INSERT INTO users (name, oidc_sub, email)
VALUES ($1, $2, $3)
RETURNING id, name, oidc_sub, email, created_at
`

type CreateUserWithOIDCParams struct {
	Name    string
	OidcSub *string
	Email   *string
}

func (q *Queries) CreateUserWithOIDC(ctx context.Context, arg CreateUserWithOIDCParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithOIDC, arg.Name, arg.OidcSub, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OidcSub,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserArticleGroups = `-- name: DeleteUserArticleGroups :exec
DELETE FROM article_groups WHERE user_id = $1
`

func (q *Queries) DeleteUserArticleGroups(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserArticleGroups, userID)
	return err
}

const deleteUserFeedTags = `-- name: DeleteUserFeedTags :exec
DELETE FROM feed_tags WHERE user_id = $1
`

func (q *Queries) DeleteUserFeedTags(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserFeedTags, userID)
	return err
}

const deleteUserFeedbackEvents = `-- name: DeleteUserFeedbackEvents :exec
DELETE FROM feedback_events WHERE user_id = $1
`

// The FK would cascade this anyway; it is explicit because feedback events are
// behavioral data and "deleting my account leaves no residue" is a promise
// worth enforcing visibly and testing directly (docs/feedback-events.md).
func (q *Queries) DeleteUserFeedbackEvents(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserFeedbackEvents, userID)
	return err
}

const deleteUserFeeds = `-- name: DeleteUserFeeds :exec
DELETE FROM user_feeds WHERE user_id = $1
`

func (q *Queries) DeleteUserFeeds(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserFeeds, userID)
	return err
}

const deleteUserFilterRules = `-- name: DeleteUserFilterRules :exec
DELETE FROM filter_rules WHERE user_id = $1
`

func (q *Queries) DeleteUserFilterRules(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserFilterRules, userID)
	return err
}

const deleteUserPreferences = `-- name: DeleteUserPreferences :exec
DELETE FROM user_preferences WHERE user_id = $1
`

func (q *Queries) DeleteUserPreferences(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserPreferences, userID)
	return err
}

const deleteUserPrompts = `-- name: DeleteUserPrompts :exec
DELETE FROM user_prompts WHERE user_id = $1
`

func (q *Queries) DeleteUserPrompts(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserPrompts, userID)
	return err
}

const deleteUserReadState = `-- name: DeleteUserReadState :exec

DELETE FROM read_state WHERE user_id = $1
`

// The following deletes back PostgresStore.DeleteUser, which runs them in one
// transaction. Tables with an ON DELETE CASCADE to users are removed by
// DeleteUserRow; the rest are deleted explicitly first.
func (q *Queries) DeleteUserReadState(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserReadState, userID)
	return err
}

const deleteUserRow = `-- name: DeleteUserRow :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUserRow(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUserRow, id)
	return err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, name, oidc_sub, email, created_at FROM users WHERE name = $1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OidcSub,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByOIDCSub = `-- name: GetUserByOIDCSub :one
SELECT id, name, oidc_sub, email, created_at FROM users WHERE oidc_sub = $1
`

func (q *Queries) GetUserByOIDCSub(ctx context.Context, oidcSub *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOIDCSub, oidcSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OidcSub,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, oidc_sub, email, created_at FROM users ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OidcSub,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserOIDCEmail = `-- name: UpdateUserOIDCEmail :exec
UPDATE users SET email = $1 WHERE id = $2
`

type UpdateUserOIDCEmailParams struct {
	Email *string
	ID    int64
}

func (q *Queries) UpdateUserOIDCEmail(ctx context.Context, arg UpdateUserOIDCEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserOIDCEmail, arg.Email, arg.ID)
	return err
}
