name: Bug Report
description: Report a bug in Herald
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Herald version (e.g., v0.1.0 or commit hash).
    validations:
      required: true

  - type: input
    id: go_version
    attributes:
      label: Go Version
      description: Output of `go version`.
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Logs, screenshots, or any other relevant context.
    validations:
      required: false
